-- loc/es_es.lua — Spanish (Spain). Machine translated (game-anchored terms);
-- corrections welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "botón",
        SLIDER   = "control deslizante",
        CYCLE    = "control deslizante",
        CHECKBOX = "casilla",
        TAB      = "pestaña",
        CARD     = "carta",
        JOKER    = "comodín",
        TAROT    = "tarot",
        PLANET   = "planeta",
        SPECTRAL = "espectral",
        VOUCHER  = "vale",
        BOOSTER  = "paquete potenciador",
        TEXT_FIELD = "campo de texto",
    },
    STATUS = { ON = "activado", OFF = "desactivado" },
    LABELS = { LOCKED = "bloqueado", EMPTY = "vacío", NOT_DISCOVERED = "No descubierto" },

    KEYS = {
        RETURN = "Intro", KPENTER = "Intro (teclado numérico)",
        LSHIFT = "Mayús izquierda", RSHIFT = "Mayús derecha",
        LCTRL = "Ctrl izquierda", RCTRL = "Ctrl derecha",
        LALT = "Alt izquierda", RALT = "Alt derecha",
        UP = "Arriba", DOWN = "Abajo", LEFT = "Izquierda", RIGHT = "Derecha",
        SPACE = "Espacio", ESCAPE = "Escape", TAB = "Tabulador", BACKSPACE = "Retroceso",
        CTRL = "Ctrl", SHIFT = "Mayús", ALT = "Alt",
        UNBOUND = "(sin asignar)",
    },

    PAD = {
        DPUP = "Cruceta arriba", DPDOWN = "Cruceta abajo",
        DPLEFT = "Cruceta izquierda", DPRIGHT = "Cruceta derecha",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Botón superior izquierdo", RIGHTSHOULDER = "Botón superior derecho",
        LEFTSTICK = "Clic de stick izquierdo", RIGHTSTICK = "Clic de stick derecho",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Gatillo izquierdo", TRIGGERRIGHT = "Gatillo derecho",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold {version} cargado.",
        UPDATE_AVAILABLE = "Actualización de Blindfold disponible: {current} a {latest}.",
        TUTORIAL_DONE = "Tutorial completado.",
    },
    RARITY = { COMMON = "común", UNCOMMON = "poco común", RARE = "raro", LEGENDARY = "legendario" },
    POSITION = { OF = "{index} de {total}" },

    SCREEN = {
        PLAYING      = "Partida",
        SHOP         = "Tienda",
        BLIND_SELECT = "Selección de ciega",
        CASH_OUT     = "Cobro",
        PACK         = "Paquete potenciador",
        GAME_OVER    = "Fin de la partida",
        MAIN_MENU    = "Menú principal",
        MENU         = "Menú",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Confirmar desbloquear todo",
        CONFIRM_ACTION = "Confirmar {action}",
        COMPLETED      = "completado",
    },

    CONTAINER = {
        HAND        = "Mano",
        JOKERS      = "Comodines",
        CONSUMABLES = "Consumibles",
        VOUCHERS    = "Vales",
        PACKS       = "Paquetes",
        DECK        = "Baraja",
        PLAYED      = "Jugadas",
        SHOP        = "Tienda",
        SHOP_GOODS  = "Vales y paquetes",
        PACK        = "Paquete",
    },

    PACK = {
        CHOOSE    = "Elige {choices} de {count}",
        CANT_SKIP = "No se puede omitir",
    },

    CARD = {
        PLAYING    = "{rank} de {suit}",
        DEBUFFED   = "debilitada",
        FACE_DOWN  = "boca abajo",
        TELL_SMALL    = "carta pequeña",
        TELL_SQUARE   = "carta cuadrada",
        TELL_HALF     = "carta de media altura",
        TELL_SHORT    = "carta corta",
        TELL_RED_BACK = "dorso rojo",
        SELL       = "venta {amount}$",
        CANT_SELL  = "no se puede vender",
        PINNED     = "fijado",
        NEW        = "nuevo",
        FORCED     = "forzada",
        WIN_STICKER = "pegatina de {stake}",
        SELECTED   = "seleccionada",
        DESELECTED = "deseleccionada",
        TIP        = "{name}, {desc}",
        RANDOM_MULT = "+{min} a +{max} {mult}, aleatorio",
        SEL_POS    = "selección {index}",
    },
    EDITION = {
        foil = "laminada", holographic = "holográfica",
        polychrome = "policroma", negative = "negativa",
    },
    SEAL = { GOLD = "sello dorado", RED = "sello rojo", BLUE = "sello azul", PURPLE = "sello morado" },

    INPUT = {
        NAV_UP = "Navegar arriba", NAV_DOWN = "Navegar abajo",
        NAV_LEFT = "Navegar a la izquierda", NAV_RIGHT = "Navegar a la derecha",
        ROW_START = "Inicio de fila", ROW_END = "Fin de fila",
        SELECT = "Seleccionar / Activar", GRAB = "Coger / Colocar",
        BACK = "Atrás / Deseleccionar", PAUSE = "Pausa",
        PLAY_HAND = "Jugar mano", DISCARD = "Descartar",
        SELL = "Vender", USE = "Usar",
        TAB_LEFT = "Pestaña anterior", TAB_RIGHT = "Pestaña siguiente",
        VIEW_DECK = "Ver baraja",
        RUN_INFO = "Información de la partida", DEBUG_DUMP = "Debug: volcar foco",
        BUFFER_NEXT_ITEM = "Búfer: elemento siguiente", BUFFER_PREV_ITEM = "Búfer: elemento anterior",
        BUFFER_NEXT = "Búfer: búfer siguiente", BUFFER_PREV = "Búfer: búfer anterior",
        INFO_HANDS = "Leer: manos restantes", INFO_DISCARDS = "Leer: descartes restantes",
        INFO_SCORE = "Leer: puntuación y objetivo", INFO_JOKERS = "Leer: huecos de comodín",
        INFO_MONEY = "Leer: dinero",
    },

    BUFFER = {
        EVENTS = "Eventos",
        GAME = "Partida",
        CARD = "Carta",
        JOKER = "Comodín",
        CONSUMABLE = "Consumible",
        CASHOUT = "Cobro",
        UI = "Interfaz",
        NONE = "Sin búferes",
        EMPTY = "El búfer {buffer} está vacío",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "{count} manos restantes",
        DISCARDS = "{count} descartes restantes",
        MONEY    = "{amount}$",
        SCORE    = "{score} de {req}",
        BLIND    = "Ciega, {name}",
        ANTE     = "Apuesta inicial, {ante} de 8",
        ROUND    = "Ronda, {round}",
        JOKERS   = "{count} de {slots} comodines",
        NOT_NOW  = "No disponible ahora",
    },

    STATS = {
        USES = "{count} usos",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, base {base}, efectivo {effective}",
        DRAWN     = "robada",
        FLIPPED   = "{count} robadas boca abajo",
    },

    BLIND = {
        REQUIREMENT = "consigue al menos {amount}",
        REWARD      = "recompensa {dollars}$",
        SKIP        = "omitir",
        NOT_CURRENT = "No es la ciega actual",
        REROLL_USED = "Ya se ha vuelto a tirar en esta apuesta inicial",
    },

    PLAY = {
        PLAY_HAND   = "Jugar mano",
        DISCARD     = "Descartar",
        SORT_RANK   = "Ordenar por valor",
        SORT_SUIT   = "Ordenar por palo",
        SORTED_RANK = "Ordenado por valor",
        SORTED_SUIT = "Ordenado por palo",
        NO_CARDS    = "No hay cartas seleccionadas",
        NO_DISCARDS = "No quedan descartes",
        CANT_SELECT = "No se puede seleccionar",
        PICKED_UP   = "Cogida, {name}",
        PICKUP_CANCELLED = "Cancelado",
        SELECTION_CLEARED = "Selección anulada",
        TUT_BLOCKED = "Sigue las instrucciones del tutorial para continuar",
        MOVED       = "Movida",
        PINNED_CANT_MOVE = "Fijado, no se puede mover",
        PLACE_LEFT    = "colocar a la izquierda de {name}",
        PLACE_BETWEEN = "colocar entre {left} y {right}",
        PLACE_RIGHT   = "colocar a la derecha de {name}",
        CANT_MOVE_HERE = "No se puede colocar aquí",
        USED        = "Usada",
        CANT_USE    = "No se puede usar ahora",
        NEEDS_TARGETS = "Requiere cartas seleccionadas en la mano",
        SOLD        = "Vendida",
        CANT_SELL   = "No se puede vender",
    },

    ROUND = {
        HAND_PLAYED = "Mano jugada, quedan {count} manos",
        DISCARDED   = "Descartado, quedan {count} descartes",
        HOOK_DISCARD   = "The Hook descarta {cards}",
        JOKER_DEBUFFED = "{name} debilitado",
        OX    = "Dinero puesto a 0$",
        TOOTH = "{amount}$ perdidos",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "gratis",
        SELL = "venta {cost}$",
        REROLL = "Volver a tirar, {cost}$",
        CANT_AFFORD = "No tienes suficiente dinero",
        NO_ROOM     = "No hay sitio",
        BOUGHT      = "Comprado",
        BOUGHT_USED = "Comprado y usado",
        REDEEMED    = "Canjeado",
        EMPTY       = "vacío",
    },

    CASHOUT = {
        LABEL         = "Cobrar",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Recompensa de ciega, {dollars}$",
        SAVED         = "Salvado por Mr. Bones",
        HANDS_ROW     = "Manos restantes, {count}, {dollars}$",
        DISCARDS_ROW  = "Descartes restantes, {count}, {dollars}$",
        INTEREST_ROW  = "Intereses, {dollars}$, {rate} por cada 5$ hasta {max}",
        JOKER         = "Comodín",
        TAG           = "Etiqueta",
    },

    RUNINFO = {
        COL_LEVEL  = "nivel",
        COL_CHIPS  = "fichas",
        COL_MULT   = "multi",
        COL_PLAYED = "jugadas",
        COL_REQS   = "requisitos",
    },

    EVENTS = {
        DESTROYED = "{name} destruida",
        ADDED     = "{name} añadida",
        HANDS     = "{amt} manos",
        DISCARDS  = "{amt} descartes",
        ANTE      = "{amt} apuesta inicial",
        ROUND     = "{amt} ronda",
    },

    SCORING = {
        HAND    = "{name}, {chips} fichas, {mult} multi",
        HAND_LEVEL = "{name} subió al nivel {level}, {chips} fichas, {mult} multi",
        HAND_LEVEL_DOWN = "{name} bajó al nivel {level}, {chips} fichas, {mult} multi",
        CHIPS   = "{amt} fichas",
        MULT    = "{amt} multi",
        XMULT   = "por {amt} multi",
        ABBR_CHIPS = "f",
        ABBR_MULT  = "m",
        JOKER_POS = "comodín en posición {n}",
        JOKER_POS_LIST = "posiciones de comodines activados: {list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} debilitado",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} fichas por {mult} multi es igual a {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Anunciar puntuación",
        HAND_PREVIEW    = "Anunciar la mano al seleccionar",
        SCORING_DETAIL  = "Detalle de puntuación",
        DETAIL_FULL     = "Completo",
        DETAIL_JOKERS   = "Solo comodines",
        DETAIL_SUMMARY  = "Resumen",
        ROUND_ACTIONS   = "Anunciar jugadas y descartes",
        KEYBINDS        = "Controles",
        ANNOUNCEMENTS   = "Anuncios",
        TUTORIAL        = "Jugar tutorial",
        UNAVAILABLE     = "Ajustes de Blindfold no disponibles",
        PRESS_KEY       = "Pulsa una tecla o botón de mando para {action}",
        BOUND           = "{action} asignado a {key}",
        CANCELLED       = "Reasignación cancelada",
        CONFLICT        = "{key} ya está asignado a {action}, reasignación cancelada",
        CLICK_ORDER     = "Puntuar cartas en orden de selección",
        CURSOR_FOLLOW   = "El cursor del juego sigue la navegación",
        ANN_TYPE        = "Anunciar tipo",
        ANN_SUBTYPE     = "Anunciar rareza",
        ANN_SELECTED    = "Anunciar selección",
        ANN_DESCRIPTION = "Anunciar descripciones",
        ANN_TOOLTIP     = "Anunciar información emergente",
        ANN_EXTRAS      = "Anunciar información de opciones",
        ANN_POSITION    = "Anunciar posición",
        ANN_CONTAINER   = "Anunciar zona",
        ANN_SCREEN      = "Anunciar cambios de pantalla",
        ANN_KEYWORDS    = "Anunciar descripciones de palabras clave",
        EV_TAGS         = "Anunciar efectos de etiquetas",
        EV_CARDS        = "Anunciar cartas creadas y destruidas",
        EV_RESOURCES    = "Anunciar cambios de recursos",
        DISCORD         = "Visitar Discord",
        PATREON         = "Apóyanos en Patreon",
        OPENING_DISCORD = "Abriendo Discord en el navegador.",
        OPENING_PATREON = "Abriendo Patreon en el navegador.",
        VIEW_DOCS       = "Ver documentación",
        VIEW_CHANGES    = "Ver cambios",
        OPENING_DOCS    = "Abriendo la documentación.",
        OPENING_CHANGES = "Abriendo los cambios.",
        SPEECH_BACKEND  = "Motor de voz",
        BACKEND_AUTO    = "Automático (el mejor disponible)",
        SCORING         = "Puntuación",
        FMT_CHIPS_GAIN  = "Anuncio de fichas ganadas",
        FMT_CHIPS_LOSS  = "Anuncio de fichas perdidas",
        FMT_MULT_GAIN   = "Anuncio de multi sumado",
        FMT_MULT_LOSS   = "Anuncio de multi restado",
        FMT_XMULT       = "Anuncio de multi multiplicado",
    },
}
