-- loc/fr.lua — French. Machine translated (game-anchored terms); corrections
-- welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "bouton",
        SLIDER   = "curseur",
        CYCLE    = "curseur",
        CHECKBOX = "case à cocher",
        TAB      = "onglet",
        CARD     = "carte",
        JOKER    = "joker",
        TAROT    = "tarot",
        PLANET   = "planète",
        SPECTRAL = "spectrale",
        VOUCHER  = "coupon",
        BOOSTER  = "booster",
        TEXT_FIELD = "champ de texte",
    },
    STATUS = { ON = "activé", OFF = "désactivé" },
    LABELS = { LOCKED = "bloqué", EMPTY = "vide", NOT_DISCOVERED = "Non découvert" },

    KEYS = {
        RETURN = "Entrée", KPENTER = "Entrée (pavé numérique)",
        LSHIFT = "Maj gauche", RSHIFT = "Maj droite",
        LCTRL = "Ctrl gauche", RCTRL = "Ctrl droite",
        LALT = "Alt gauche", RALT = "Alt droite",
        UP = "Haut", DOWN = "Bas", LEFT = "Gauche", RIGHT = "Droite",
        SPACE = "Espace", ESCAPE = "Échap", TAB = "Tab", BACKSPACE = "Retour arrière",
        CTRL = "Ctrl", SHIFT = "Maj", ALT = "Alt",
        UNBOUND = "(non assigné)",
    },

    PAD = {
        DPUP = "Croix haut", DPDOWN = "Croix bas",
        DPLEFT = "Croix gauche", DPRIGHT = "Croix droite",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Gâchette haute gauche", RIGHTSHOULDER = "Gâchette haute droite",
        LEFTSTICK = "Clic stick gauche", RIGHTSTICK = "Clic stick droit",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Gâchette gauche", TRIGGERRIGHT = "Gâchette droite",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold {version} chargé.",
        UPDATE_AVAILABLE = "Mise à jour de Blindfold disponible : {current} vers {latest}.",
        TUTORIAL_DONE = "Tutoriel terminé.",
    },
    RARITY = { COMMON = "commun", UNCOMMON = "inhabituel", RARE = "rare", LEGENDARY = "légendaire" },
    POSITION = { OF = "{index} sur {total}" },

    SCREEN = {
        PLAYING      = "Partie",
        SHOP         = "Boutique",
        BLIND_SELECT = "Choix de la blinde",
        CASH_OUT     = "Encaissement",
        PACK         = "Booster",
        GAME_OVER    = "Partie terminée",
        MAIN_MENU    = "Menu principal",
        MENU         = "Menu",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Confirmer tout débloquer",
        CONFIRM_ACTION = "Confirmer {action}",
        COMPLETED      = "terminé",
    },

    CONTAINER = {
        HAND        = "Main",
        JOKERS      = "Jokers",
        CONSUMABLES = "Consommables",
        VOUCHERS    = "Coupons",
        PACKS       = "Boosters",
        DECK        = "Jeu",
        PLAYED      = "Jouées",
        SHOP        = "Boutique",
        SHOP_GOODS  = "Coupons et boosters",
        PACK        = "Booster",
    },

    PACK = {
        CHOOSE    = "Choisissez {choices} sur {count}",
        CANT_SKIP = "Impossible de passer",
    },

    CARD = {
        PLAYING    = "{rank} de {suit}",
        DEBUFFED   = "affaiblie",
        FACE_DOWN  = "face cachée",
        TELL_SMALL    = "petite carte",
        TELL_SQUARE   = "carte carrée",
        TELL_HALF     = "carte demi-hauteur",
        TELL_SHORT    = "carte courte",
        TELL_RED_BACK = "dos rouge",
        SELL       = "vente {amount}$",
        CANT_SELL  = "invendable",
        PINNED     = "épinglé",
        NEW        = "nouveau",
        FORCED     = "forcée",
        WIN_STICKER = "autocollant {stake}",
        SELECTED   = "sélectionnée",
        DESELECTED = "désélectionnée",
        TIP        = "{name}, {desc}",
        RANDOM_MULT = "+{min} à +{max} {mult}, aléatoire",
        SEL_POS    = "sélection {index}",
    },
    EDITION = {
        foil = "métallisée", holographic = "holographique",
        polychrome = "polychrome", negative = "négative",
    },
    SEAL = { GOLD = "sceau doré", RED = "sceau rouge", BLUE = "sceau bleu", PURPLE = "sceau violet" },

    INPUT = {
        NAV_UP = "Naviguer vers le haut", NAV_DOWN = "Naviguer vers le bas",
        NAV_LEFT = "Naviguer à gauche", NAV_RIGHT = "Naviguer à droite",
        ROW_START = "Début de rangée", ROW_END = "Fin de rangée",
        SELECT = "Sélectionner / Activer", GRAB = "Prendre / Poser",
        BACK = "Retour / Tout désélectionner", PAUSE = "Pause",
        PLAY_HAND = "Jouer la main", DISCARD = "Défausser",
        SELL = "Vendre", USE = "Utiliser",
        TAB_LEFT = "Onglet précédent", TAB_RIGHT = "Onglet suivant",
        VIEW_DECK = "Voir le jeu",
        RUN_INFO = "Infos de la partie", DEBUG_DUMP = "Debug : afficher le focus",
        BUFFER_NEXT_ITEM = "Tampon : élément suivant", BUFFER_PREV_ITEM = "Tampon : élément précédent",
        BUFFER_NEXT = "Tampon : tampon suivant", BUFFER_PREV = "Tampon : tampon précédent",
        INFO_HANDS = "Lire : mains restantes", INFO_DISCARDS = "Lire : défausses restantes",
        INFO_SCORE = "Lire : score et objectif", INFO_JOKERS = "Lire : emplacements de joker",
        INFO_MONEY = "Lire : argent",
    },

    BUFFER = {
        EVENTS = "Événements",
        GAME = "Partie",
        CARD = "Carte",
        JOKER = "Joker",
        CONSUMABLE = "Consommable",
        CASHOUT = "Encaissement",
        UI = "Interface",
        NONE = "Aucun tampon",
        EMPTY = "Le tampon {buffer} est vide",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "{count} mains restantes",
        DISCARDS = "{count} défausses restantes",
        MONEY    = "{amount}$",
        SCORE    = "{score} sur {req}",
        BLIND    = "Blinde, {name}",
        ANTE     = "Mise initiale, {ante} sur 8",
        ROUND    = "Manche, {round}",
        JOKERS   = "{count} jokers sur {slots}",
        NOT_NOW  = "Indisponible pour le moment",
    },

    STATS = {
        USES = "{count} utilisations",
    },

    DECK_VIEW = {
        NAME_DESC = "{name} : {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, base {base}, effectif {effective}",
        DRAWN     = "piochée",
        FLIPPED   = "{count} piochées face cachée",
    },

    BLIND = {
        REQUIREMENT = "marquez au moins {amount}",
        REWARD      = "récompense {dollars}$",
        SKIP        = "passer",
        NOT_CURRENT = "Pas la blinde actuelle",
        REROLL_USED = "Déjà relancé pour cette mise initiale",
    },

    PLAY = {
        PLAY_HAND   = "Jouer la main",
        DISCARD     = "Défausser",
        SORT_RANK   = "Trier par valeur",
        SORT_SUIT   = "Trier par couleur",
        SORTED_RANK = "Trié par valeur",
        SORTED_SUIT = "Trié par couleur",
        NO_CARDS    = "Aucune carte sélectionnée",
        NO_DISCARDS = "Aucune défausse restante",
        CANT_SELECT = "Sélection impossible",
        PICKED_UP   = "Prise, {name}",
        PICKUP_CANCELLED = "Annulé",
        SELECTION_CLEARED = "Sélection annulée",
        TUT_BLOCKED = "Suivez les instructions du tutoriel pour continuer",
        MOVED       = "Déplacée",
        PINNED_CANT_MOVE = "Épinglé, déplacement impossible",
        PLACE_LEFT    = "poser à gauche de {name}",
        PLACE_BETWEEN = "poser entre {left} et {right}",
        PLACE_RIGHT   = "poser à droite de {name}",
        CANT_MOVE_HERE = "Impossible de poser ici",
        USED        = "Utilisée",
        CANT_USE    = "Inutilisable pour le moment",
        NEEDS_TARGETS = "Nécessite des cartes sélectionnées en main",
        SOLD        = "Vendue",
        CANT_SELL   = "Invendable",
    },

    ROUND = {
        HAND_PLAYED = "Main jouée, {count} mains restantes",
        DISCARDED   = "Défaussé, {count} défausses restantes",
        HOOK_DISCARD   = "The Hook défausse {cards}",
        JOKER_DEBUFFED = "{name} affaibli",
        OX    = "Argent mis à 0$",
        TOOTH = "{amount}$ perdus",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "gratuit",
        SELL = "vente {cost}$",
        REROLL = "Relancer, {cost}$",
        CANT_AFFORD = "Pas assez d'argent",
        NO_ROOM     = "Pas de place",
        BOUGHT      = "Acheté",
        BOUGHT_USED = "Acheté et utilisé",
        REDEEMED    = "Échangé",
        EMPTY       = "vide",
    },

    CASHOUT = {
        LABEL         = "Encaisser",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Récompense de blinde, {dollars}$",
        SAVED         = "Sauvé par Mr. Bones",
        HANDS_ROW     = "Mains restantes, {count}, {dollars}$",
        DISCARDS_ROW  = "Défausses restantes, {count}, {dollars}$",
        INTEREST_ROW  = "Intérêts, {dollars}$, {rate} par tranche de 5$ jusqu'à {max}",
        JOKER         = "Joker",
        TAG           = "Badge",
    },

    RUNINFO = {
        COL_LEVEL  = "niveau",
        COL_CHIPS  = "jetons",
        COL_MULT   = "multi",
        COL_PLAYED = "jouées",
        COL_REQS   = "conditions",
    },

    EVENTS = {
        DESTROYED = "{name} détruite",
        ADDED     = "{name} ajoutée",
        HANDS     = "{amt} mains",
        DISCARDS  = "{amt} défausses",
        ANTE      = "{amt} ante",
        ROUND     = "{amt} manche",
    },

    SCORING = {
        HAND    = "{name}, {chips} jetons, {mult} multi",
        HAND_LEVEL = "{name} amélioré au niveau {level}, {chips} jetons, {mult} multi",
        HAND_LEVEL_DOWN = "{name} descendu au niveau {level}, {chips} jetons, {mult} multi",
        CHIPS   = "{amt} jetons",
        MULT    = "{amt} multi",
        XMULT   = "fois {amt} multi",
        ABBR_CHIPS = "j",
        ABBR_MULT  = "m",
        JOKER_POS = "joker en position {n}",
        JOKER_POS_LIST = "positions des jokers déclenchés : {list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} affaibli",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} jetons fois {mult} multi égale {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Annoncer le score",
        HAND_PREVIEW    = "Annoncer la main pendant la sélection",
        SCORING_DETAIL  = "Détail du score",
        DETAIL_FULL     = "Complet",
        DETAIL_JOKERS   = "Jokers uniquement",
        DETAIL_SUMMARY  = "Résumé",
        ROUND_ACTIONS   = "Annoncer les mains jouées et défausses",
        KEYBINDS        = "Raccourcis clavier",
        ANNOUNCEMENTS   = "Annonces",
        TUTORIAL        = "Jouer le tutoriel",
        UNAVAILABLE     = "Paramètres Blindfold indisponibles",
        PRESS_KEY       = "Appuyez sur une touche ou un bouton de manette pour {action}",
        BOUND           = "{action} assigné à {key}",
        CANCELLED       = "Réassignation annulée",
        CONFLICT        = "{key} est déjà assigné à {action}, réassignation annulée",
        CLICK_ORDER     = "Compter les cartes dans l'ordre de sélection",
        CURSOR_FOLLOW   = "Le curseur du jeu suit la navigation",
        ANN_TYPE        = "Annoncer le type",
        ANN_SUBTYPE     = "Annoncer la rareté",
        ANN_SELECTED    = "Annoncer la sélection",
        ANN_DESCRIPTION = "Annoncer les descriptions",
        ANN_TOOLTIP     = "Annoncer les infobulles",
        ANN_EXTRAS      = "Annoncer les infos d'option",
        ANN_POSITION    = "Annoncer la position",
        ANN_CONTAINER   = "Annoncer la zone",
        ANN_SCREEN      = "Annoncer les changements d'écran",
        ANN_KEYWORDS    = "Annoncer les descriptions des mots-clés",
        EV_TAGS         = "Annoncer les effets des étiquettes",
        EV_CARDS        = "Annoncer les cartes créées et détruites",
        EV_RESOURCES    = "Annoncer les changements de ressources",
        DISCORD         = "Visiter le Discord",
        PATREON         = "Soutenir sur Patreon",
        OPENING_DISCORD = "Ouverture de Discord dans le navigateur.",
        OPENING_PATREON = "Ouverture de Patreon dans le navigateur.",
        VIEW_DOCS       = "Voir la documentation",
        VIEW_CHANGES    = "Voir les modifications",
        OPENING_DOCS    = "Ouverture de la documentation.",
        OPENING_CHANGES = "Ouverture des modifications.",
        SPEECH_BACKEND  = "Moteur vocal",
        BACKEND_AUTO    = "Auto (meilleur disponible)",
        SCORING         = "Score",
        FMT_CHIPS_GAIN  = "Annonce des jetons gagnés",
        FMT_CHIPS_LOSS  = "Annonce des jetons perdus",
        FMT_MULT_GAIN   = "Annonce du multi ajouté",
        FMT_MULT_LOSS   = "Annonce du multi retiré",
        FMT_XMULT       = "Annonce du multi multiplié",
    },
}
