-- loc/id.lua — Indonesian. Machine translated (game-anchored terms);
-- corrections welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "tombol",
        SLIDER   = "penggeser",
        CYCLE    = "penggeser",
        CHECKBOX = "kotak centang",
        TAB      = "tab",
        CARD     = "kartu",
        JOKER    = "joker",
        TAROT    = "tarot",
        PLANET   = "planet",
        SPECTRAL = "spektral",
        VOUCHER  = "voucher",
        BOOSTER  = "booster pack",
        TEXT_FIELD = "kolom teks",
    },
    STATUS = { ON = "nyala", OFF = "mati" },
    LABELS = { LOCKED = "terkunci", EMPTY = "kosong", NOT_DISCOVERED = "Belum ditemukan" },

    KEYS = {
        RETURN = "Enter", KPENTER = "Enter (numpad)",
        LSHIFT = "Shift kiri", RSHIFT = "Shift kanan",
        LCTRL = "Ctrl kiri", RCTRL = "Ctrl kanan",
        LALT = "Alt kiri", RALT = "Alt kanan",
        UP = "Atas", DOWN = "Bawah", LEFT = "Kiri", RIGHT = "Kanan",
        SPACE = "Spasi", ESCAPE = "Escape", TAB = "Tab", BACKSPACE = "Backspace",
        CTRL = "Ctrl", SHIFT = "Shift", ALT = "Alt",
        UNBOUND = "(belum diatur)",
    },

    PAD = {
        DPUP = "D-pad atas", DPDOWN = "D-pad bawah",
        DPLEFT = "D-pad kiri", DPRIGHT = "D-pad kanan",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Bumper kiri", RIGHTSHOULDER = "Bumper kanan",
        LEFTSTICK = "Klik stik kiri", RIGHTSTICK = "Klik stik kanan",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Trigger kiri", TRIGGERRIGHT = "Trigger kanan",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold {version} dimuat.",
        UPDATE_AVAILABLE = "Pembaruan Blindfold tersedia: {current} ke {latest}.",
        TUTORIAL_DONE = "Tutorial selesai.",
    },
    RARITY = { COMMON = "umum", UNCOMMON = "tidak umum", RARE = "langka", LEGENDARY = "legendaris" },
    POSITION = { OF = "{index} dari {total}" },

    SCREEN = {
        PLAYING      = "Bermain",
        SHOP         = "Toko",
        BLIND_SELECT = "Pilih blind",
        CASH_OUT     = "Pencairan",
        PACK         = "Booster pack",
        GAME_OVER    = "Permainan berakhir",
        MAIN_MENU    = "Menu utama",
        MENU         = "Menu",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Konfirmasi buka semua",
        CONFIRM_ACTION = "Konfirmasi {action}",
        COMPLETED      = "selesai",
    },

    CONTAINER = {
        HAND        = "Kartu di tangan",
        JOKERS      = "Joker",
        CONSUMABLES = "Kartu habis pakai",
        VOUCHERS    = "Voucher",
        PACKS       = "Pack",
        DECK        = "Deck",
        PLAYED      = "Dimainkan",
        SHOP        = "Toko",
        SHOP_GOODS  = "Voucher dan pack",
        PACK        = "Pack",
    },

    PACK = {
        CHOOSE    = "Pilih {choices} dari {count}",
        CANT_SKIP = "Tidak bisa dilewati",
    },

    CARD = {
        PLAYING    = "{rank} {suit}",
        DEBUFFED   = "dilemahkan",
        FACE_DOWN  = "tertutup",
        TELL_SMALL    = "kartu kecil",
        TELL_SQUARE   = "kartu persegi",
        TELL_HALF     = "kartu setengah tinggi",
        TELL_SHORT    = "kartu pendek",
        TELL_RED_BACK = "punggung merah",
        SELL       = "jual {amount}$",
        CANT_SELL  = "tidak bisa dijual",
        PINNED     = "disematkan",
        NEW        = "baru",
        FORCED     = "dipaksa",
        WIN_STICKER = "stiker {stake}",
        SELECTED   = "dipilih",
        DESELECTED = "batal dipilih",
        TIP        = "{name}, {desc}",
        RANDOM_MULT = "+{min} sampai +{max} {mult}, acak",
        SEL_POS    = "pilihan {index}",
    },
    EDITION = {
        foil = "foil", holographic = "hologram",
        polychrome = "polikrom", negative = "negatif",
    },
    SEAL = { GOLD = "seal emas", RED = "seal merah", BLUE = "seal biru", PURPLE = "seal ungu" },

    INPUT = {
        NAV_UP = "Navigasi ke atas", NAV_DOWN = "Navigasi ke bawah",
        NAV_LEFT = "Navigasi ke kiri", NAV_RIGHT = "Navigasi ke kanan",
        ROW_START = "Awal baris", ROW_END = "Akhir baris",
        SELECT = "Pilih / Aktifkan", GRAB = "Ambil / Letakkan",
        BACK = "Kembali / Batalkan pilihan", PAUSE = "Jeda",
        PLAY_HAND = "Mainkan kartu", DISCARD = "Buang",
        SELL = "Jual", USE = "Pakai",
        TAB_LEFT = "Tab sebelumnya", TAB_RIGHT = "Tab berikutnya",
        VIEW_DECK = "Lihat deck",
        RUN_INFO = "Info permainan", DEBUG_DUMP = "Debug: dump fokus",
        BUFFER_NEXT_ITEM = "Buffer: item berikutnya", BUFFER_PREV_ITEM = "Buffer: item sebelumnya",
        BUFFER_NEXT = "Buffer: buffer berikutnya", BUFFER_PREV = "Buffer: buffer sebelumnya",
        INFO_HANDS = "Baca: sisa giliran main", INFO_DISCARDS = "Baca: sisa buangan",
        INFO_SCORE = "Baca: skor dan target", INFO_JOKERS = "Baca: slot joker",
        INFO_MONEY = "Baca: uang",
    },

    BUFFER = {
        EVENTS = "Peristiwa",
        GAME = "Permainan",
        CARD = "Kartu",
        JOKER = "Joker",
        CONSUMABLE = "Kartu habis pakai",
        CASHOUT = "Pencairan",
        UI = "Antarmuka",
        NONE = "Tidak ada buffer",
        EMPTY = "Buffer {buffer} kosong",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "sisa {count} giliran main",
        DISCARDS = "sisa {count} buangan",
        MONEY    = "{amount}$",
        SCORE    = "{score} dari {req}",
        BLIND    = "Blind, {name}",
        ANTE     = "Ante, {ante} dari 8",
        ROUND    = "Babak, {round}",
        JOKERS   = "{count} dari {slots} joker",
        NOT_NOW  = "Sedang tidak tersedia",
    },

    STATS = {
        USES = "{count} kali dipakai",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, dasar {base}, efektif {effective}",
        DRAWN     = "sudah ditarik",
        FLIPPED   = "{count} ditarik tertutup",
    },

    BLIND = {
        REQUIREMENT = "raih skor minimal {amount}",
        REWARD      = "hadiah {dollars}$",
        SKIP        = "lewati",
        NOT_CURRENT = "Bukan blind saat ini",
        REROLL_USED = "Sudah mengocok ulang di ante ini",
    },

    PLAY = {
        PLAY_HAND   = "Mainkan kartu",
        DISCARD     = "Buang",
        SORT_RANK   = "Urutkan berdasarkan angka",
        SORT_SUIT   = "Urutkan berdasarkan lambang",
        SORTED_RANK = "Diurutkan berdasarkan angka",
        SORTED_SUIT = "Diurutkan berdasarkan lambang",
        NO_CARDS    = "Tidak ada kartu yang dipilih",
        NO_DISCARDS = "Tidak ada sisa buangan",
        CANT_SELECT = "Tidak bisa dipilih",
        PICKED_UP   = "Diambil, {name}",
        PICKUP_CANCELLED = "Dibatalkan",
        SELECTION_CLEARED = "Pilihan dibersihkan",
        TUT_BLOCKED = "Ikuti petunjuk tutorial untuk melanjutkan",
        MOVED       = "Dipindahkan",
        PINNED_CANT_MOVE = "Disematkan, tidak bisa dipindah",
        PLACE_LEFT    = "letakkan di kiri {name}",
        PLACE_BETWEEN = "letakkan di antara {left} dan {right}",
        PLACE_RIGHT   = "letakkan di kanan {name}",
        CANT_MOVE_HERE = "Tidak bisa diletakkan di sini",
        USED        = "Dipakai",
        CANT_USE    = "Sekarang tidak bisa dipakai",
        NEEDS_TARGETS = "Perlu kartu tangan yang dipilih",
        SOLD        = "Terjual",
        CANT_SELL   = "Tidak bisa dijual",
    },

    ROUND = {
        HAND_PLAYED = "Kartu dimainkan, sisa {count} giliran",
        DISCARDED   = "Dibuang, sisa {count} buangan",
        HOOK_DISCARD   = "The Hook membuang {cards}",
        JOKER_DEBUFFED = "{name} dilemahkan",
        OX    = "Uang menjadi 0$",
        TOOTH = "Kehilangan {amount}$",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "gratis",
        SELL = "jual {cost}$",
        REROLL = "Kocok ulang, {cost}$",
        CANT_AFFORD = "Uang tidak cukup",
        NO_ROOM     = "Tidak ada tempat",
        BOUGHT      = "Dibeli",
        BOUGHT_USED = "Dibeli dan dipakai",
        REDEEMED    = "Ditukarkan",
        EMPTY       = "kosong",
    },

    CASHOUT = {
        LABEL         = "Cairkan",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Hadiah blind, {dollars}$",
        SAVED         = "Diselamatkan Mr. Bones",
        HANDS_ROW     = "Sisa giliran main, {count}, {dollars}$",
        DISCARDS_ROW  = "Sisa buangan, {count}, {dollars}$",
        INTEREST_ROW  = "Bunga, {dollars}$, {rate} per 5$ hingga {max}",
        JOKER         = "Joker",
        TAG           = "Tag",
    },

    RUNINFO = {
        COL_LEVEL  = "level",
        COL_CHIPS  = "chip",
        COL_MULT   = "mult",
        COL_PLAYED = "dimainkan",
        COL_REQS   = "syarat",
    },

    EVENTS = {
        DESTROYED = "{name} dihancurkan",
        ADDED     = "{name} ditambahkan",
        HANDS     = "{amt} giliran main",
        DISCARDS  = "{amt} buangan",
        ANTE      = "{amt} ante",
        ROUND     = "{amt} ronde",
    },

    SCORING = {
        HAND    = "{name}, {chips} chip, {mult} mult",
        HAND_LEVEL = "{name} naik ke level {level}, {chips} chip, {mult} mult",
        HAND_LEVEL_DOWN = "{name} turun ke level {level}, {chips} chip, {mult} mult",
        CHIPS   = "{amt} chip",
        MULT    = "{amt} mult",
        XMULT   = "kali {amt} mult",
        ABBR_CHIPS = "c",
        ABBR_MULT  = "m",
        JOKER_POS = "joker di posisi {n}",
        JOKER_POS_LIST = "posisi joker terpicu: {list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} dilemahkan",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} chip kali {mult} mult sama dengan {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Bacakan skor",
        HAND_PREVIEW    = "Bacakan kombinasi saat memilih",
        SCORING_DETAIL  = "Detail skor",
        DETAIL_FULL     = "Lengkap",
        DETAIL_JOKERS   = "Hanya joker",
        DETAIL_SUMMARY  = "Ringkasan",
        ROUND_ACTIONS   = "Bacakan main dan buang",
        KEYBINDS        = "Pengaturan tombol",
        ANNOUNCEMENTS   = "Pengumuman",
        TUTORIAL        = "Mainkan tutorial",
        UNAVAILABLE     = "Pengaturan Blindfold tidak tersedia",
        PRESS_KEY       = "Tekan tombol keyboard atau kontroler untuk {action}",
        BOUND           = "{action} diatur ke {key}",
        CANCELLED       = "Pengaturan ulang dibatalkan",
        CONFLICT        = "{key} sudah diatur ke {action}, pengaturan ulang dibatalkan",
        CLICK_ORDER     = "Nilai kartu sesuai urutan pemilihan",
        CURSOR_FOLLOW   = "Kursor game mengikuti navigasi",
        ANN_TYPE        = "Bacakan jenis",
        ANN_SUBTYPE     = "Bacakan kelangkaan",
        ANN_SELECTED    = "Bacakan status pilihan",
        ANN_DESCRIPTION = "Bacakan deskripsi",
        ANN_TOOLTIP     = "Bacakan tooltip",
        ANN_EXTRAS      = "Bacakan info opsi",
        ANN_POSITION    = "Bacakan posisi",
        ANN_CONTAINER   = "Bacakan area",
        ANN_SCREEN      = "Bacakan pergantian layar",
        ANN_KEYWORDS    = "Bacakan deskripsi kata kunci",
        EV_TAGS         = "Bacakan efek tag",
        EV_CARDS        = "Bacakan kartu yang dibuat dan dihancurkan",
        EV_RESOURCES    = "Bacakan perubahan sumber daya",
        DISCORD         = "Kunjungi Discord",
        PATREON         = "Dukung di Patreon",
        OPENING_DISCORD = "Membuka Discord di browser.",
        OPENING_PATREON = "Membuka Patreon di browser.",
        VIEW_DOCS       = "Lihat Dokumentasi",
        VIEW_CHANGES    = "Lihat Perubahan",
        OPENING_DOCS    = "Membuka dokumentasi.",
        OPENING_CHANGES = "Membuka perubahan.",
        SPEECH_BACKEND  = "Backend suara",
        BACKEND_AUTO    = "Otomatis (terbaik yang tersedia)",
        SCORING         = "Skor",
        FMT_CHIPS_GAIN  = "Pengumuman chip diperoleh",
        FMT_CHIPS_LOSS  = "Pengumuman chip hilang",
        FMT_MULT_GAIN   = "Pengumuman mult tambah",
        FMT_MULT_LOSS   = "Pengumuman mult kurang",
        FMT_XMULT       = "Pengumuman mult kali",
    },
}
