-- loc/it.lua — Italian. Machine translated (game-anchored terms); corrections
-- welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "pulsante",
        SLIDER   = "cursore",
        CYCLE    = "cursore",
        CHECKBOX = "casella",
        TAB      = "scheda",
        CARD     = "carta",
        JOKER    = "jolly",
        TAROT    = "tarocco",
        PLANET   = "pianeta",
        SPECTRAL = "spettrale",
        VOUCHER  = "buono",
        BOOSTER  = "busta di espansione",
        TEXT_FIELD = "campo di testo",
    },
    STATUS = { ON = "attivo", OFF = "disattivo" },
    LABELS = { LOCKED = "bloccato", EMPTY = "vuoto", NOT_DISCOVERED = "Non scoperto" },

    KEYS = {
        RETURN = "Invio", KPENTER = "Invio (tastierino)",
        LSHIFT = "Maiusc sinistro", RSHIFT = "Maiusc destro",
        LCTRL = "Ctrl sinistro", RCTRL = "Ctrl destro",
        LALT = "Alt sinistro", RALT = "Alt destro",
        UP = "Su", DOWN = "Giù", LEFT = "Sinistra", RIGHT = "Destra",
        SPACE = "Spazio", ESCAPE = "Esc", TAB = "Tab", BACKSPACE = "Backspace",
        CTRL = "Ctrl", SHIFT = "Maiusc", ALT = "Alt",
        UNBOUND = "(non assegnato)",
    },

    PAD = {
        DPUP = "Croce su", DPDOWN = "Croce giù",
        DPLEFT = "Croce sinistra", DPRIGHT = "Croce destra",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Dorsale sinistro", RIGHTSHOULDER = "Dorsale destro",
        LEFTSTICK = "Clic stick sinistro", RIGHTSTICK = "Clic stick destro",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Grilletto sinistro", TRIGGERRIGHT = "Grilletto destro",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold {version} caricato.",
        UPDATE_AVAILABLE = "Aggiornamento di Blindfold disponibile: {current} a {latest}.",
        TUTORIAL_DONE = "Tutorial completato.",
    },
    RARITY = { COMMON = "comune", UNCOMMON = "non comune", RARE = "raro", LEGENDARY = "leggendario" },
    POSITION = { OF = "{index} di {total}" },

    SCREEN = {
        PLAYING      = "Partita",
        SHOP         = "Negozio",
        BLIND_SELECT = "Scelta del buio",
        CASH_OUT     = "Incasso",
        PACK         = "Busta di espansione",
        GAME_OVER    = "Partita finita",
        MAIN_MENU    = "Menu principale",
        MENU         = "Menu",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Conferma sblocca tutto",
        CONFIRM_ACTION = "Conferma {action}",
        COMPLETED      = "completata",
    },

    CONTAINER = {
        HAND        = "Mano",
        JOKERS      = "Jolly",
        CONSUMABLES = "Consumabili",
        VOUCHERS    = "Buoni",
        PACKS       = "Buste",
        DECK        = "Mazzo",
        PLAYED      = "Giocate",
        SHOP        = "Negozio",
        SHOP_GOODS  = "Buoni e buste",
        PACK        = "Busta",
    },

    PACK = {
        CHOOSE    = "Scegli {choices} di {count}",
        CANT_SKIP = "Impossibile saltare",
    },

    CARD = {
        PLAYING    = "{rank} di {suit}",
        DEBUFFED   = "indebolita",
        FACE_DOWN  = "coperta",
        TELL_SMALL    = "carta piccola",
        TELL_SQUARE   = "carta quadrata",
        TELL_HALF     = "carta a mezza altezza",
        TELL_SHORT    = "carta corta",
        TELL_RED_BACK = "dorso rosso",
        SELL       = "vendita {amount}$",
        CANT_SELL  = "non vendibile",
        PINNED     = "fissato",
        NEW        = "nuovo",
        FORCED     = "forzata",
        WIN_STICKER = "adesivo {stake}",
        SELECTED   = "selezionata",
        DESELECTED = "deselezionata",
        TIP        = "{name}, {desc}",
        RANDOM_MULT = "da +{min} a +{max} {mult}, casuale",
        SEL_POS    = "selezione {index}",
    },
    EDITION = {
        foil = "laminata", holographic = "olografica",
        polychrome = "policroma", negative = "negativa",
    },
    SEAL = { GOLD = "sigillo dorato", RED = "sigillo rosso", BLUE = "sigillo blu", PURPLE = "sigillo viola" },

    INPUT = {
        NAV_UP = "Naviga su", NAV_DOWN = "Naviga giù",
        NAV_LEFT = "Naviga a sinistra", NAV_RIGHT = "Naviga a destra",
        ROW_START = "Inizio riga", ROW_END = "Fine riga",
        SELECT = "Seleziona / Attiva", GRAB = "Prendi / Posa",
        BACK = "Indietro / Deseleziona", PAUSE = "Pausa",
        PLAY_HAND = "Gioca la mano", DISCARD = "Scarta",
        SELL = "Vendi", USE = "Usa",
        TAB_LEFT = "Scheda precedente", TAB_RIGHT = "Scheda successiva",
        VIEW_DECK = "Vedi mazzo",
        RUN_INFO = "Info partita", DEBUG_DUMP = "Debug: scarica focus",
        BUFFER_NEXT_ITEM = "Buffer: elemento successivo", BUFFER_PREV_ITEM = "Buffer: elemento precedente",
        BUFFER_NEXT = "Buffer: buffer successivo", BUFFER_PREV = "Buffer: buffer precedente",
        INFO_HANDS = "Leggi: mani rimanenti", INFO_DISCARDS = "Leggi: scarti rimanenti",
        INFO_SCORE = "Leggi: punteggio e obiettivo", INFO_JOKERS = "Leggi: spazi jolly",
        INFO_MONEY = "Leggi: soldi",
    },

    BUFFER = {
        EVENTS = "Eventi",
        GAME = "Partita",
        CARD = "Carta",
        JOKER = "Jolly",
        CONSUMABLE = "Consumabile",
        CASHOUT = "Incasso",
        UI = "Interfaccia",
        NONE = "Nessun buffer",
        EMPTY = "Il buffer {buffer} è vuoto",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "{count} mani rimanenti",
        DISCARDS = "{count} scarti rimanenti",
        MONEY    = "{amount}$",
        SCORE    = "{score} di {req}",
        BLIND    = "Buio, {name}",
        ANTE     = "Ante, {ante} di 8",
        ROUND    = "Round, {round}",
        JOKERS   = "{count} di {slots} jolly",
        NOT_NOW  = "Non disponibile ora",
    },

    STATS = {
        USES = "{count} utilizzi",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, base {base}, effettivo {effective}",
        DRAWN     = "pescata",
        FLIPPED   = "{count} pescate coperte",
    },

    BLIND = {
        REQUIREMENT = "totalizza almeno {amount}",
        REWARD      = "ricompensa {dollars}$",
        SKIP        = "salta",
        NOT_CURRENT = "Non è il buio attuale",
        REROLL_USED = "Già ritirato in questo ante",
    },

    PLAY = {
        PLAY_HAND   = "Gioca la mano",
        DISCARD     = "Scarta",
        SORT_RANK   = "Ordina per valore",
        SORT_SUIT   = "Ordina per seme",
        SORTED_RANK = "Ordinato per valore",
        SORTED_SUIT = "Ordinato per seme",
        NO_CARDS    = "Nessuna carta selezionata",
        NO_DISCARDS = "Nessuno scarto rimanente",
        CANT_SELECT = "Impossibile selezionare",
        PICKED_UP   = "Presa, {name}",
        PICKUP_CANCELLED = "Annullato",
        SELECTION_CLEARED = "Selezione annullata",
        TUT_BLOCKED = "Segui le istruzioni del tutorial per continuare",
        MOVED       = "Spostata",
        PINNED_CANT_MOVE = "Fissato, non spostabile",
        PLACE_LEFT    = "posa a sinistra di {name}",
        PLACE_BETWEEN = "posa tra {left} e {right}",
        PLACE_RIGHT   = "posa a destra di {name}",
        CANT_MOVE_HERE = "Impossibile posare qui",
        USED        = "Usata",
        CANT_USE    = "Non utilizzabile ora",
        NEEDS_TARGETS = "Richiede carte selezionate in mano",
        SOLD        = "Venduta",
        CANT_SELL   = "Non vendibile",
    },

    ROUND = {
        HAND_PLAYED = "Mano giocata, {count} mani rimanenti",
        DISCARDED   = "Scartato, {count} scarti rimanenti",
        HOOK_DISCARD   = "The Hook scarta {cards}",
        JOKER_DEBUFFED = "{name} indebolito",
        OX    = "Soldi azzerati",
        TOOTH = "{amount}$ persi",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "gratis",
        SELL = "vendita {cost}$",
        REROLL = "Ritira, {cost}$",
        CANT_AFFORD = "Soldi insufficienti",
        NO_ROOM     = "Niente spazio",
        BOUGHT      = "Comprato",
        BOUGHT_USED = "Comprato e usato",
        REDEEMED    = "Riscattato",
        EMPTY       = "vuoto",
    },

    CASHOUT = {
        LABEL         = "Incassa",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Ricompensa del buio, {dollars}$",
        SAVED         = "Salvato da Mr. Bones",
        HANDS_ROW     = "Mani rimanenti, {count}, {dollars}$",
        DISCARDS_ROW  = "Scarti rimanenti, {count}, {dollars}$",
        INTEREST_ROW  = "Interessi, {dollars}$, {rate} ogni 5$ fino a {max}",
        JOKER         = "Jolly",
        TAG           = "Patto",
    },

    RUNINFO = {
        COL_LEVEL  = "livello",
        COL_CHIPS  = "gettoni",
        COL_MULT   = "molt",
        COL_PLAYED = "giocate",
        COL_REQS   = "requisiti",
    },

    EVENTS = {
        DESTROYED = "{name} distrutta",
        ADDED     = "{name} aggiunta",
        HANDS     = "{amt} mani",
        DISCARDS  = "{amt} scarti",
        ANTE      = "{amt} ante",
        ROUND     = "{amt} round",
    },

    SCORING = {
        HAND    = "{name}, {chips} gettoni, {mult} molt",
        HAND_LEVEL = "{name} salito al livello {level}, {chips} gettoni, {mult} molt",
        HAND_LEVEL_DOWN = "{name} sceso al livello {level}, {chips} gettoni, {mult} molt",
        CHIPS   = "{amt} gettoni",
        MULT    = "{amt} molt",
        XMULT   = "per {amt} molt",
        ABBR_CHIPS = "g",
        ABBR_MULT  = "m",
        JOKER_POS = "jolly in posizione {n}",
        JOKER_POS_LIST = "posizioni dei jolly attivati: {list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} indebolito",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} gettoni per {mult} molt fa {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Annuncia il punteggio",
        HAND_PREVIEW    = "Annuncia la mano durante la selezione",
        SCORING_DETAIL  = "Dettaglio punteggio",
        DETAIL_FULL     = "Completo",
        DETAIL_JOKERS   = "Solo jolly",
        DETAIL_SUMMARY  = "Riepilogo",
        ROUND_ACTIONS   = "Annuncia giocate e scarti",
        KEYBINDS        = "Comandi",
        ANNOUNCEMENTS   = "Annunci",
        TUTORIAL        = "Gioca il tutorial",
        UNAVAILABLE     = "Impostazioni Blindfold non disponibili",
        PRESS_KEY       = "Premi un tasto o un pulsante del controller per {action}",
        BOUND           = "{action} assegnato a {key}",
        CANCELLED       = "Riassegnazione annullata",
        CONFLICT        = "{key} è già assegnato a {action}, riassegnazione annullata",
        CLICK_ORDER     = "Conteggia le carte nell'ordine di selezione",
        CURSOR_FOLLOW   = "Il cursore del gioco segue la navigazione",
        ANN_TYPE        = "Annuncia il tipo",
        ANN_SUBTYPE     = "Annuncia la rarità",
        ANN_SELECTED    = "Annuncia la selezione",
        ANN_DESCRIPTION = "Annuncia le descrizioni",
        ANN_TOOLTIP     = "Annuncia i suggerimenti",
        ANN_EXTRAS      = "Annuncia le info delle opzioni",
        ANN_POSITION    = "Annuncia la posizione",
        ANN_CONTAINER   = "Annuncia l'area",
        ANN_SCREEN      = "Annuncia i cambi di schermata",
        ANN_KEYWORDS    = "Annuncia le descrizioni delle parole chiave",
        EV_TAGS         = "Annuncia gli effetti dei tag",
        EV_CARDS        = "Annuncia carte create e distrutte",
        EV_RESOURCES    = "Annuncia i cambiamenti di risorse",
        DISCORD         = "Visita il Discord",
        PATREON         = "Sostienici su Patreon",
        OPENING_DISCORD = "Apertura di Discord nel browser.",
        OPENING_PATREON = "Apertura di Patreon nel browser.",
        VIEW_DOCS       = "Mostra documentazione",
        VIEW_CHANGES    = "Mostra modifiche",
        OPENING_DOCS    = "Apertura della documentazione.",
        OPENING_CHANGES = "Apertura delle modifiche.",
        SPEECH_BACKEND  = "Motore vocale",
        BACKEND_AUTO    = "Auto (migliore disponibile)",
        SCORING         = "Punteggio",
        FMT_CHIPS_GAIN  = "Annuncio gettoni guadagnati",
        FMT_CHIPS_LOSS  = "Annuncio gettoni persi",
        FMT_MULT_GAIN   = "Annuncio molt aggiunto",
        FMT_MULT_LOSS   = "Annuncio molt sottratto",
        FMT_XMULT       = "Annuncio molt moltiplicato",
    },
}
