-- loc/ja.lua — Japanese. Machine translated (game-anchored terms); corrections
-- welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "ボタン",
        SLIDER   = "スライダー",
        CYCLE    = "スライダー",
        CHECKBOX = "チェックボックス",
        TAB      = "タブ",
        CARD     = "カード",
        JOKER    = "ジョーカー",
        TAROT    = "タロット",
        PLANET   = "プラネット",
        SPECTRAL = "スペクトラル",
        VOUCHER  = "バウチャー",
        BOOSTER  = "ブースターパック",
        TEXT_FIELD = "テキスト入力欄",
    },
    STATUS = { ON = "オン", OFF = "オフ" },
    LABELS = { LOCKED = "ロック中", EMPTY = "空", NOT_DISCOVERED = "未発見" },

    KEYS = {
        RETURN = "Enter", KPENTER = "テンキーEnter",
        LSHIFT = "左Shift", RSHIFT = "右Shift",
        LCTRL = "左Ctrl", RCTRL = "右Ctrl",
        LALT = "左Alt", RALT = "右Alt",
        UP = "上", DOWN = "下", LEFT = "左", RIGHT = "右",
        SPACE = "スペース", ESCAPE = "Escape", TAB = "Tab", BACKSPACE = "Backspace",
        CTRL = "Ctrl", SHIFT = "Shift", ALT = "Alt",
        UNBOUND = "（未割り当て）",
    },

    PAD = {
        DPUP = "十字キー上", DPDOWN = "十字キー下",
        DPLEFT = "十字キー左", DPRIGHT = "十字キー右",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Lボタン", RIGHTSHOULDER = "Rボタン",
        LEFTSTICK = "左スティック押し込み", RIGHTSTICK = "右スティック押し込み",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "左トリガー", TRIGGERRIGHT = "右トリガー",
        CHORD = "{mod}＋{button}",
    },

    MISC = {
        LOADED = "Blindfold {version} を読み込みました。",
        UPDATE_AVAILABLE = "Blindfoldの更新があります：{current}から{latest}へ。",
        TUTORIAL_DONE = "チュートリアル完了。",
    },
    RARITY = { COMMON = "コモン", UNCOMMON = "アンコモン", RARE = "レア", LEGENDARY = "レジェンダリー" },
    POSITION = { OF = "{total}枚中{index}枚目" },

    SCREEN = {
        PLAYING      = "プレイ中",
        SHOP         = "ショップ",
        BLIND_SELECT = "ブラインド選択",
        CASH_OUT     = "キャッシュアウト",
        PACK         = "ブースターパック",
        GAME_OVER    = "ゲームオーバー",
        MAIN_MENU    = "メインメニュー",
        MENU         = "メニュー",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "全アンロックを確認",
        CONFIRM_ACTION = "{action}を確認",
        COMPLETED      = "クリア済み",
    },

    CONTAINER = {
        HAND        = "手札",
        JOKERS      = "ジョーカー",
        CONSUMABLES = "消費アイテム",
        VOUCHERS    = "バウチャー",
        PACKS       = "パック",
        DECK        = "デッキ",
        PLAYED      = "プレイ済み",
        SHOP        = "ショップ",
        SHOP_GOODS  = "バウチャーとパック",
        PACK        = "パック",
    },

    PACK = {
        CHOOSE    = "{count}枚から{choices}枚選択",
        CANT_SKIP = "スキップできません",
    },

    CARD = {
        PLAYING    = "{suit}の{rank}",
        DEBUFFED   = "弱体化",
        FACE_DOWN  = "裏向き",
        TELL_SMALL    = "小さいカード",
        TELL_SQUARE   = "正方形のカード",
        TELL_HALF     = "半分の高さのカード",
        TELL_SHORT    = "低いカード",
        TELL_RED_BACK = "赤い裏面",
        SELL       = "売値{amount}$",
        CANT_SELL  = "売却不可",
        PINNED     = "固定",
        NEW        = "新着",
        FORCED     = "強制選択",
        WIN_STICKER = "{stake}ステッカー",
        SELECTED   = "選択",
        DESELECTED = "選択解除",
        TIP        = "{name}、{desc}",
        RANDOM_MULT = "+{min}～+{max}{mult}、ランダム",
        SEL_POS    = "選択{index}",
    },
    EDITION = {
        foil = "フォイル", holographic = "ホログラフィック",
        polychrome = "ポリクローム", negative = "ネガ",
    },
    SEAL = { GOLD = "ゴールドシール", RED = "レッドシール", BLUE = "ブルーシール", PURPLE = "パープルシール" },

    INPUT = {
        NAV_UP = "上へ移動", NAV_DOWN = "下へ移動",
        NAV_LEFT = "左へ移動", NAV_RIGHT = "右へ移動",
        ROW_START = "行の先頭", ROW_END = "行の末尾",
        SELECT = "選択／決定", GRAB = "持ち上げる／置く",
        BACK = "戻る／選択解除", PAUSE = "ポーズ",
        PLAY_HAND = "ハンドをプレイ", DISCARD = "ディスカード",
        SELL = "売却", USE = "使用",
        TAB_LEFT = "前のタブ", TAB_RIGHT = "次のタブ",
        VIEW_DECK = "デッキを見る",
        RUN_INFO = "ラン情報", DEBUG_DUMP = "デバッグ: フォーカスをダンプ",
        BUFFER_NEXT_ITEM = "バッファ: 次の項目", BUFFER_PREV_ITEM = "バッファ: 前の項目",
        BUFFER_NEXT = "バッファ: 次のバッファ", BUFFER_PREV = "バッファ: 前のバッファ",
        INFO_HANDS = "読み上げ: 残りハンド", INFO_DISCARDS = "読み上げ: 残りディスカード",
        INFO_SCORE = "読み上げ: スコアと目標", INFO_JOKERS = "読み上げ: ジョーカー枠",
        INFO_MONEY = "読み上げ: 資金",
    },

    BUFFER = {
        EVENTS = "イベント",
        GAME = "ゲーム",
        CARD = "カード",
        JOKER = "ジョーカー",
        CONSUMABLE = "消費アイテム",
        CASHOUT = "キャッシュアウト",
        UI = "UI",
        NONE = "バッファなし",
        EMPTY = "{buffer}バッファは空です",
        CURRENT = "{buffer}、{item}",
    },
    GAME = {
        HANDS    = "残りハンド{count}",
        DISCARDS = "残りディスカード{count}",
        MONEY    = "{amount}$",
        SCORE    = "{req}中{score}",
        BLIND    = "ブラインド、{name}",
        ANTE     = "アンティ、8中{ante}",
        ROUND    = "ラウンド、{round}",
        JOKERS   = "ジョーカー{slots}枠中{count}",
        NOT_NOW  = "現在は利用できません",
    },

    STATS = {
        USES = "使用回数{count}",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}、{count}",
        TALLY_MOD = "{label}、基本{base}、実効{effective}",
        DRAWN     = "引いた",
        FLIPPED   = "{count}枚が裏向きで配られた",
    },

    BLIND = {
        REQUIREMENT = "{amount}以上のスコア",
        REWARD      = "報酬{dollars}$",
        SKIP        = "スキップ",
        NOT_CURRENT = "現在のブラインドではありません",
        REROLL_USED = "このアンティでは再抽選済み",
    },

    PLAY = {
        PLAY_HAND   = "ハンドをプレイ",
        DISCARD     = "ディスカード",
        SORT_RANK   = "ランクで並べ替え",
        SORT_SUIT   = "スートで並べ替え",
        SORTED_RANK = "ランク順に並べ替えました",
        SORTED_SUIT = "スート順に並べ替えました",
        NO_CARDS    = "カードが選択されていません",
        NO_DISCARDS = "残りディスカードがありません",
        CANT_SELECT = "選択できません",
        PICKED_UP   = "持ち上げました、{name}",
        PICKUP_CANCELLED = "キャンセルしました",
        SELECTION_CLEARED = "選択を解除しました",
        TUT_BLOCKED = "続行するにはチュートリアルの指示に従ってください",
        MOVED       = "移動しました",
        PINNED_CANT_MOVE = "固定されているため移動できません",
        PLACE_LEFT    = "{name}の左に置く",
        PLACE_BETWEEN = "{left}と{right}の間に置く",
        PLACE_RIGHT   = "{name}の右に置く",
        CANT_MOVE_HERE = "ここには置けません",
        USED        = "使用しました",
        CANT_USE    = "今は使用できません",
        NEEDS_TARGETS = "手札のカードを選択してください",
        SOLD        = "売却しました",
        CANT_SELL   = "売却できません",
    },

    ROUND = {
        HAND_PLAYED = "ハンドをプレイ、残り{count}ハンド",
        DISCARDED   = "ディスカード、残り{count}回",
        HOOK_DISCARD   = "The Hookが{cards}を捨てました",
        JOKER_DEBUFFED = "{name}が弱体化",
        OX    = "資金が0$になりました",
        TOOTH = "{amount}$失いました",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "無料",
        SELL = "売値{cost}$",
        REROLL = "リロール、{cost}$",
        CANT_AFFORD = "資金が足りません",
        NO_ROOM     = "空きがありません",
        BOUGHT      = "購入しました",
        BOUGHT_USED = "購入して使用しました",
        REDEEMED    = "引き換えました",
        EMPTY       = "空",
    },

    CASHOUT = {
        LABEL         = "キャッシュアウト",
        TOTAL         = "{dollars}$",
        ROW           = "{label}、{dollars}$",
        BLIND_ROW     = "ブラインド報酬、{dollars}$",
        SAVED         = "Mr. Bonesに救われた",
        HANDS_ROW     = "残りハンド、{count}、{dollars}$",
        DISCARDS_ROW  = "残りディスカード、{count}、{dollars}$",
        INTEREST_ROW  = "利子、{dollars}$、5$ごとに{rate}、最大{max}",
        JOKER         = "ジョーカー",
        TAG           = "タグ",
    },

    RUNINFO = {
        COL_LEVEL  = "レベル",
        COL_CHIPS  = "チップ",
        COL_MULT   = "倍率",
        COL_PLAYED = "プレイ回数",
        COL_REQS   = "条件",
    },

    EVENTS = {
        DESTROYED = "{name}が破壊されました",
        ADDED     = "{name}が追加されました",
        HANDS     = "ハンド{amt}",
        DISCARDS  = "ディスカード{amt}",
        ANTE      = "アンティ{amt}",
        ROUND     = "ラウンド{amt}",
    },

    SCORING = {
        HAND    = "{name}、チップ{chips}、倍率{mult}",
        HAND_LEVEL = "{name}がレベル{level}に上昇、チップ{chips}、倍率{mult}",
        HAND_LEVEL_DOWN = "{name}がレベル{level}に低下、チップ{chips}、倍率{mult}",
        CHIPS   = "チップ{amt}",
        MULT    = "倍率{amt}",
        XMULT   = "倍率{amt}倍",
        ABBR_CHIPS = "チップ",
        ABBR_MULT  = "倍率",
        JOKER_POS = "ポジション{n}のジョーカー",
        JOKER_POS_LIST = "発動したジョーカーのポジション：{list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source}が弱体化",
        SOURCE  = "{source}、{effect}",
        TOTAL   = "チップ{chips}かける倍率{mult}で{score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "スコアを読み上げる",
        HAND_PREVIEW    = "選択中に役を読み上げる",
        SCORING_DETAIL  = "スコアの詳細度",
        DETAIL_FULL     = "すべて",
        DETAIL_JOKERS   = "ジョーカーのみ",
        DETAIL_SUMMARY  = "要約",
        ROUND_ACTIONS   = "プレイとディスカードを読み上げる",
        KEYBINDS        = "キー設定",
        ANNOUNCEMENTS   = "読み上げ設定",
        TUTORIAL        = "チュートリアルをプレイ",
        UNAVAILABLE     = "Blindfoldの設定を利用できません",
        PRESS_KEY       = "{action}に割り当てるキーまたはボタンを押してください",
        BOUND           = "{action}を{key}に割り当てました",
        CANCELLED       = "割り当てをキャンセルしました",
        CONFLICT        = "{key}は既に{action}に割り当てられています。割り当てをキャンセルしました",
        CLICK_ORDER     = "選択した順番でカードをスコア計算",
        CURSOR_FOLLOW   = "ゲームカーソルがナビゲーションに追従",
        ANN_TYPE        = "種類を読み上げる",
        ANN_SUBTYPE     = "レアリティを読み上げる",
        ANN_SELECTED    = "選択状態を読み上げる",
        ANN_DESCRIPTION = "説明を読み上げる",
        ANN_TOOLTIP     = "ツールチップを読み上げる",
        ANN_EXTRAS      = "オプション情報を読み上げる",
        ANN_POSITION    = "位置を読み上げる",
        ANN_CONTAINER   = "エリアを読み上げる",
        ANN_SCREEN      = "画面の切り替えを読み上げる",
        ANN_KEYWORDS    = "キーワードの説明を読み上げる",
        EV_TAGS         = "タグ効果を読み上げる",
        EV_CARDS        = "生成・破壊されたカードを読み上げる",
        EV_RESOURCES    = "リソースの変化を読み上げる",
        DISCORD         = "Discordを開く",
        PATREON         = "Patreonで支援する",
        OPENING_DISCORD = "ブラウザでDiscordを開いています。",
        OPENING_PATREON = "ブラウザでPatreonを開いています。",
        VIEW_DOCS       = "ドキュメントを表示",
        VIEW_CHANGES    = "変更履歴を表示",
        OPENING_DOCS    = "ドキュメントを開いています。",
        OPENING_CHANGES = "変更履歴を開いています。",
        SPEECH_BACKEND  = "音声バックエンド",
        BACKEND_AUTO    = "自動（利用可能な最適）",
        SCORING         = "スコア",
        FMT_CHIPS_GAIN  = "獲得チップの読み上げ",
        FMT_CHIPS_LOSS  = "失ったチップの読み上げ",
        FMT_MULT_GAIN   = "倍率加算の読み上げ",
        FMT_MULT_LOSS   = "倍率減算の読み上げ",
        FMT_XMULT       = "倍率乗算の読み上げ",
    },
}
