-- loc/ko.lua — Korean. Machine translated (game-anchored terms); corrections
-- welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "버튼",
        SLIDER   = "슬라이더",
        CYCLE    = "슬라이더",
        CHECKBOX = "체크박스",
        TAB      = "탭",
        CARD     = "카드",
        JOKER    = "조커",
        TAROT    = "타로",
        PLANET   = "행성",
        SPECTRAL = "스펙트럴",
        VOUCHER  = "바우처",
        BOOSTER  = "부스터 팩",
        TEXT_FIELD = "텍스트 입력란",
    },
    STATUS = { ON = "켜짐", OFF = "꺼짐" },
    LABELS = { LOCKED = "잠김", EMPTY = "비어 있음", NOT_DISCOVERED = "미발견" },

    KEYS = {
        RETURN = "Enter", KPENTER = "숫자패드 Enter",
        LSHIFT = "왼쪽 Shift", RSHIFT = "오른쪽 Shift",
        LCTRL = "왼쪽 Ctrl", RCTRL = "오른쪽 Ctrl",
        LALT = "왼쪽 Alt", RALT = "오른쪽 Alt",
        UP = "위", DOWN = "아래", LEFT = "왼쪽", RIGHT = "오른쪽",
        SPACE = "스페이스", ESCAPE = "Escape", TAB = "Tab", BACKSPACE = "Backspace",
        CTRL = "Ctrl", SHIFT = "Shift", ALT = "Alt",
        UNBOUND = "(할당 안 됨)",
    },

    PAD = {
        DPUP = "십자키 위", DPDOWN = "십자키 아래",
        DPLEFT = "십자키 왼쪽", DPRIGHT = "십자키 오른쪽",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "왼쪽 범퍼", RIGHTSHOULDER = "오른쪽 범퍼",
        LEFTSTICK = "왼쪽 스틱 클릭", RIGHTSTICK = "오른쪽 스틱 클릭",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "왼쪽 트리거", TRIGGERRIGHT = "오른쪽 트리거",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold {version} 로드 완료.",
        UPDATE_AVAILABLE = "Blindfold 업데이트가 있습니다: {current}에서 {latest}(으)로.",
        TUTORIAL_DONE = "튜토리얼 완료.",
    },
    RARITY = { COMMON = "일반", UNCOMMON = "고급", RARE = "희귀", LEGENDARY = "전설" },
    POSITION = { OF = "{total}개 중 {index}번째" },

    SCREEN = {
        PLAYING      = "플레이 중",
        SHOP         = "상점",
        BLIND_SELECT = "블라인드 선택",
        CASH_OUT     = "정산",
        PACK         = "부스터 팩",
        GAME_OVER    = "게임 오버",
        MAIN_MENU    = "메인 메뉴",
        MENU         = "메뉴",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "모두 잠금 해제 확인",
        CONFIRM_ACTION = "{action} 확인",
        COMPLETED      = "완료",
    },

    CONTAINER = {
        HAND        = "손패",
        JOKERS      = "조커",
        CONSUMABLES = "소모품",
        VOUCHERS    = "바우처",
        PACKS       = "팩",
        DECK        = "덱",
        PLAYED      = "플레이한 카드",
        SHOP        = "상점",
        SHOP_GOODS  = "바우처와 팩",
        PACK        = "팩",
    },

    PACK = {
        CHOOSE    = "{count}개 중 {choices}개 선택",
        CANT_SKIP = "건너뛸 수 없음",
    },

    CARD = {
        PLAYING    = "{suit} {rank}",
        DEBUFFED   = "약화됨",
        FACE_DOWN  = "뒷면",
        TELL_SMALL    = "작은 카드",
        TELL_SQUARE   = "정사각형 카드",
        TELL_HALF     = "절반 높이 카드",
        TELL_SHORT    = "낮은 카드",
        TELL_RED_BACK = "빨간 뒷면",
        SELL       = "판매가 {amount}$",
        CANT_SELL  = "판매 불가",
        PINNED     = "고정됨",
        NEW        = "신규",
        FORCED     = "강제 선택",
        WIN_STICKER = "{stake} 스티커",
        SELECTED   = "선택됨",
        DESELECTED = "선택 해제됨",
        TIP        = "{name}, {desc}",
        RANDOM_MULT = "+{min}~+{max} {mult}, 무작위",
        SEL_POS    = "선택 {index}",
    },
    EDITION = {
        foil = "포일", holographic = "홀로그램",
        polychrome = "폴리크롬", negative = "네거티브",
    },
    SEAL = { GOLD = "금색 봉인", RED = "빨간색 봉인", BLUE = "파란색 봉인", PURPLE = "보라색 봉인" },

    INPUT = {
        NAV_UP = "위로 이동", NAV_DOWN = "아래로 이동",
        NAV_LEFT = "왼쪽으로 이동", NAV_RIGHT = "오른쪽으로 이동",
        ROW_START = "줄 처음", ROW_END = "줄 끝",
        SELECT = "선택 / 실행", GRAB = "집기 / 놓기",
        BACK = "뒤로 / 선택 해제", PAUSE = "일시정지",
        PLAY_HAND = "핸드 플레이", DISCARD = "버리기",
        SELL = "판매", USE = "사용",
        TAB_LEFT = "이전 탭", TAB_RIGHT = "다음 탭",
        VIEW_DECK = "덱 보기",
        RUN_INFO = "런 정보", DEBUG_DUMP = "디버그: 포커스 덤프",
        BUFFER_NEXT_ITEM = "버퍼: 다음 항목", BUFFER_PREV_ITEM = "버퍼: 이전 항목",
        BUFFER_NEXT = "버퍼: 다음 버퍼", BUFFER_PREV = "버퍼: 이전 버퍼",
        INFO_HANDS = "읽기: 남은 핸드", INFO_DISCARDS = "읽기: 남은 버리기",
        INFO_SCORE = "읽기: 점수와 목표", INFO_JOKERS = "읽기: 조커 슬롯",
        INFO_MONEY = "읽기: 돈",
    },

    BUFFER = {
        EVENTS = "이벤트",
        GAME = "게임",
        CARD = "카드",
        JOKER = "조커",
        CONSUMABLE = "소모품",
        CASHOUT = "정산",
        UI = "UI",
        NONE = "버퍼 없음",
        EMPTY = "{buffer} 버퍼가 비어 있음",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "남은 핸드 {count}",
        DISCARDS = "남은 버리기 {count}",
        MONEY    = "{amount}$",
        SCORE    = "{req} 중 {score}",
        BLIND    = "블라인드, {name}",
        ANTE     = "앤티, 8 중 {ante}",
        ROUND    = "라운드, {round}",
        JOKERS   = "조커 {slots}칸 중 {count}",
        NOT_NOW  = "지금은 확인할 수 없음",
    },

    STATS = {
        USES = "{count}회 사용",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, 기본 {base}, 실제 {effective}",
        DRAWN     = "뽑음",
        FLIPPED   = "{count}장이 뒷면으로 뽑힘",
    },

    BLIND = {
        REQUIREMENT = "최소 {amount}점 필요",
        REWARD      = "보상 {dollars}$",
        SKIP        = "건너뛰기",
        NOT_CURRENT = "현재 블라인드가 아님",
        REROLL_USED = "이번 앤티에서 이미 리롤함",
    },

    PLAY = {
        PLAY_HAND   = "핸드 플레이",
        DISCARD     = "버리기",
        SORT_RANK   = "숫자순 정렬",
        SORT_SUIT   = "무늬순 정렬",
        SORTED_RANK = "숫자순으로 정렬됨",
        SORTED_SUIT = "무늬순으로 정렬됨",
        NO_CARDS    = "선택된 카드 없음",
        NO_DISCARDS = "남은 버리기 없음",
        CANT_SELECT = "선택할 수 없음",
        PICKED_UP   = "집었음, {name}",
        PICKUP_CANCELLED = "취소됨",
        SELECTION_CLEARED = "선택 해제됨",
        TUT_BLOCKED = "계속하려면 튜토리얼 안내를 따르세요",
        MOVED       = "이동됨",
        PINNED_CANT_MOVE = "고정되어 이동 불가",
        PLACE_LEFT    = "{name} 왼쪽에 놓기",
        PLACE_BETWEEN = "{left}와 {right} 사이에 놓기",
        PLACE_RIGHT   = "{name} 오른쪽에 놓기",
        CANT_MOVE_HERE = "여기에는 놓을 수 없음",
        USED        = "사용함",
        CANT_USE    = "지금은 사용할 수 없음",
        NEEDS_TARGETS = "손패에서 카드를 선택해야 함",
        SOLD        = "판매함",
        CANT_SELL   = "판매할 수 없음",
    },

    ROUND = {
        HAND_PLAYED = "핸드 플레이, 남은 핸드 {count}",
        DISCARDED   = "버림, 남은 버리기 {count}",
        HOOK_DISCARD   = "The Hook가 {cards}를 버림",
        JOKER_DEBUFFED = "{name} 약화됨",
        OX    = "돈이 0$가 됨",
        TOOTH = "{amount}$ 잃음",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "무료",
        SELL = "판매가 {cost}$",
        REROLL = "리롤, {cost}$",
        CANT_AFFORD = "돈이 부족함",
        NO_ROOM     = "공간 없음",
        BOUGHT      = "구매함",
        BOUGHT_USED = "구매 후 사용함",
        REDEEMED    = "사용함",
        EMPTY       = "비어 있음",
    },

    CASHOUT = {
        LABEL         = "정산",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "블라인드 보상, {dollars}$",
        SAVED         = "Mr. Bones 덕분에 살아남음",
        HANDS_ROW     = "남은 핸드, {count}, {dollars}$",
        DISCARDS_ROW  = "남은 버리기, {count}, {dollars}$",
        INTEREST_ROW  = "이자, {dollars}$, 5$당 {rate}, 최대 {max}",
        JOKER         = "조커",
        TAG           = "태그",
    },

    RUNINFO = {
        COL_LEVEL  = "레벨",
        COL_CHIPS  = "칩",
        COL_MULT   = "배수",
        COL_PLAYED = "플레이 횟수",
        COL_REQS   = "조건",
    },

    EVENTS = {
        DESTROYED = "{name} 파괴됨",
        ADDED     = "{name} 추가됨",
        HANDS     = "핸드 {amt}",
        DISCARDS  = "버리기 {amt}",
        ANTE      = "앤티 {amt}",
        ROUND     = "라운드 {amt}",
    },

    SCORING = {
        HAND    = "{name}, 칩 {chips}, 배수 {mult}",
        HAND_LEVEL = "{name} 레벨 {level}로 상승, 칩 {chips}, 배수 {mult}",
        HAND_LEVEL_DOWN = "{name} 레벨 {level}로 하락, 칩 {chips}, 배수 {mult}",
        CHIPS   = "칩 {amt}",
        MULT    = "배수 {amt}",
        XMULT   = "배수 {amt}배",
        ABBR_CHIPS = "칩",
        ABBR_MULT  = "배수",
        JOKER_POS = "{n}번 위치 조커",
        JOKER_POS_LIST = "발동한 조커 위치: {list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} 약화됨",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "칩 {chips} 곱하기 배수 {mult}은 {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "점수 계산 읽기",
        HAND_PREVIEW    = "선택 중 족보 읽기",
        SCORING_DETAIL  = "점수 상세도",
        DETAIL_FULL     = "전체",
        DETAIL_JOKERS   = "조커만",
        DETAIL_SUMMARY  = "요약",
        ROUND_ACTIONS   = "플레이와 버리기 읽기",
        KEYBINDS        = "키 설정",
        ANNOUNCEMENTS   = "알림 설정",
        TUTORIAL        = "튜토리얼 플레이",
        UNAVAILABLE     = "Blindfold 설정을 사용할 수 없음",
        PRESS_KEY       = "{action}에 할당할 키 또는 컨트롤러 버튼을 누르세요",
        BOUND           = "{action}이(가) {key}에 할당됨",
        CANCELLED       = "재할당 취소됨",
        CONFLICT        = "{key}은(는) 이미 {action}에 할당되어 있어 재할당이 취소됨",
        CLICK_ORDER     = "선택한 순서대로 카드 점수 계산",
        CURSOR_FOLLOW   = "게임 커서가 탐색을 따라 이동",
        ANN_TYPE        = "종류 읽기",
        ANN_SUBTYPE     = "희귀도 읽기",
        ANN_SELECTED    = "선택 상태 읽기",
        ANN_DESCRIPTION = "설명 읽기",
        ANN_TOOLTIP     = "툴팁 읽기",
        ANN_EXTRAS      = "옵션 정보 읽기",
        ANN_POSITION    = "위치 읽기",
        ANN_CONTAINER   = "영역 읽기",
        ANN_SCREEN      = "화면 전환 읽기",
        ANN_KEYWORDS    = "키워드 설명 읽기",
        EV_TAGS         = "태그 효과 알림",
        EV_CARDS        = "생성/파괴된 카드 알림",
        EV_RESOURCES    = "자원 변화 알림",
        DISCORD         = "Discord 방문",
        PATREON         = "Patreon에서 후원하기",
        OPENING_DISCORD = "브라우저에서 Discord를 여는 중입니다.",
        OPENING_PATREON = "브라우저에서 Patreon을 여는 중입니다.",
        VIEW_DOCS       = "설명서 보기",
        VIEW_CHANGES    = "변경 사항 보기",
        OPENING_DOCS    = "설명서를 여는 중입니다.",
        OPENING_CHANGES = "변경 사항을 여는 중입니다.",
        SPEECH_BACKEND  = "음성 백엔드",
        BACKEND_AUTO    = "자동(사용 가능한 최적)",
        SCORING         = "점수",
        FMT_CHIPS_GAIN  = "획득 칩 알림",
        FMT_CHIPS_LOSS  = "잃은 칩 알림",
        FMT_MULT_GAIN   = "배수 증가 알림",
        FMT_MULT_LOSS   = "배수 감소 알림",
        FMT_XMULT       = "배수 곱하기 알림",
    },
}
