-- loc/nl.lua — Dutch. Machine translated (game-anchored terms); corrections
-- welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "knop",
        SLIDER   = "schuifregelaar",
        CYCLE    = "schuifregelaar",
        CHECKBOX = "selectievakje",
        TAB      = "tabblad",
        CARD     = "kaart",
        JOKER    = "joker",
        TAROT    = "tarot",
        PLANET   = "planeet",
        SPECTRAL = "spectraal",
        VOUCHER  = "voucher",
        BOOSTER  = "boosterpakket",
        TEXT_FIELD = "tekstveld",
    },
    STATUS = { ON = "aan", OFF = "uit" },
    LABELS = { LOCKED = "vergrendeld", EMPTY = "leeg", NOT_DISCOVERED = "Niet ontdekt" },

    KEYS = {
        RETURN = "Enter", KPENTER = "Enter (numeriek)",
        LSHIFT = "Linker Shift", RSHIFT = "Rechter Shift",
        LCTRL = "Linker Ctrl", RCTRL = "Rechter Ctrl",
        LALT = "Linker Alt", RALT = "Rechter Alt",
        UP = "Omhoog", DOWN = "Omlaag", LEFT = "Links", RIGHT = "Rechts",
        SPACE = "Spatie", ESCAPE = "Escape", TAB = "Tab", BACKSPACE = "Backspace",
        CTRL = "Ctrl", SHIFT = "Shift", ALT = "Alt",
        UNBOUND = "(niet toegewezen)",
    },

    PAD = {
        DPUP = "D-pad omhoog", DPDOWN = "D-pad omlaag",
        DPLEFT = "D-pad links", DPRIGHT = "D-pad rechts",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Linker bumper", RIGHTSHOULDER = "Rechter bumper",
        LEFTSTICK = "Linker stick klik", RIGHTSTICK = "Rechter stick klik",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Linker trigger", TRIGGERRIGHT = "Rechter trigger",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold {version} geladen.",
        UPDATE_AVAILABLE = "Blindfold-update beschikbaar: {current} naar {latest}.",
        TUTORIAL_DONE = "Tutorial voltooid.",
    },
    RARITY = { COMMON = "gewone", UNCOMMON = "ongewone", RARE = "zeldzame", LEGENDARY = "legendarische" },
    POSITION = { OF = "{index} van {total}" },

    SCREEN = {
        PLAYING      = "Spelen",
        SHOP         = "Winkel",
        BLIND_SELECT = "Blindkeuze",
        CASH_OUT     = "Uitbetaling",
        PACK         = "Boosterpakket",
        GAME_OVER    = "Game over",
        MAIN_MENU    = "Hoofdmenu",
        MENU         = "Menu",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Alles vrijspelen bevestigen",
        CONFIRM_ACTION = "{action} bevestigen",
        COMPLETED      = "voltooid",
    },

    CONTAINER = {
        HAND        = "Hand",
        JOKERS      = "Jokers",
        CONSUMABLES = "Verbruiksitems",
        VOUCHERS    = "Vouchers",
        PACKS       = "Pakketten",
        DECK        = "Kaartspel",
        PLAYED      = "Gespeeld",
        SHOP        = "Winkel",
        SHOP_GOODS  = "Vouchers en pakketten",
        PACK        = "Pakket",
    },

    PACK = {
        CHOOSE    = "Kies {choices} van {count}",
        CANT_SKIP = "Kan niet overslaan",
    },

    CARD = {
        PLAYING    = "{suit} {rank}",
        DEBUFFED   = "verzwakt",
        FACE_DOWN  = "omgekeerd",
        TELL_SMALL    = "kleine kaart",
        TELL_SQUARE   = "vierkante kaart",
        TELL_HALF     = "halfhoge kaart",
        TELL_SHORT    = "korte kaart",
        TELL_RED_BACK = "rode achterkant",
        SELL       = "verkoop {amount}$",
        CANT_SELL  = "niet verkoopbaar",
        PINNED     = "vastgepind",
        NEW        = "nieuw",
        FORCED     = "gedwongen",
        WIN_STICKER = "{stake}-sticker",
        SELECTED   = "geselecteerd",
        DESELECTED = "gedeselecteerd",
        TIP        = "{name}, {desc}",
        RANDOM_MULT = "+{min} tot +{max} {mult}, willekeurig",
        SEL_POS    = "selectie {index}",
    },
    EDITION = {
        foil = "folie", holographic = "holografisch",
        polychrome = "polychroom", negative = "negatief",
    },
    SEAL = { GOLD = "gouden zegel", RED = "rode zegel", BLUE = "blauwe zegel", PURPLE = "paarse zegel" },

    INPUT = {
        NAV_UP = "Omhoog navigeren", NAV_DOWN = "Omlaag navigeren",
        NAV_LEFT = "Links navigeren", NAV_RIGHT = "Rechts navigeren",
        ROW_START = "Begin van rij", ROW_END = "Einde van rij",
        SELECT = "Selecteren / Activeren", GRAB = "Oppakken / Neerleggen",
        BACK = "Terug / Deselecteren", PAUSE = "Pauze",
        PLAY_HAND = "Hand spelen", DISCARD = "Weggooien",
        SELL = "Verkopen", USE = "Gebruiken",
        TAB_LEFT = "Vorig tabblad", TAB_RIGHT = "Volgend tabblad",
        VIEW_DECK = "Kaartspel bekijken",
        RUN_INFO = "Run-info", DEBUG_DUMP = "Debug: focus dumpen",
        BUFFER_NEXT_ITEM = "Buffer: volgend item", BUFFER_PREV_ITEM = "Buffer: vorig item",
        BUFFER_NEXT = "Buffer: volgende buffer", BUFFER_PREV = "Buffer: vorige buffer",
        INFO_HANDS = "Voorlezen: resterende handen", INFO_DISCARDS = "Voorlezen: resterende weggooibeurten",
        INFO_SCORE = "Voorlezen: score en doel", INFO_JOKERS = "Voorlezen: jokerplekken",
        INFO_MONEY = "Voorlezen: geld",
    },

    BUFFER = {
        EVENTS = "Gebeurtenissen",
        GAME = "Spel",
        CARD = "Kaart",
        JOKER = "Joker",
        CONSUMABLE = "Verbruiksitem",
        CASHOUT = "Uitbetaling",
        UI = "Interface",
        NONE = "Geen buffers",
        EMPTY = "Buffer {buffer} is leeg",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "{count} handen over",
        DISCARDS = "{count} weggooibeurten over",
        MONEY    = "{amount}$",
        SCORE    = "{score} van {req}",
        BLIND    = "Blind, {name}",
        ANTE     = "Ante, {ante} van 8",
        ROUND    = "Ronde, {round}",
        JOKERS   = "{count} van {slots} jokers",
        NOT_NOW  = "Nu niet beschikbaar",
    },

    STATS = {
        USES = "{count} keer gebruikt",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, basis {base}, effectief {effective}",
        DRAWN     = "getrokken",
        FLIPPED   = "{count} omgekeerd getrokken",
    },

    BLIND = {
        REQUIREMENT = "scoor ten minste {amount}",
        REWARD      = "beloning {dollars}$",
        SKIP        = "overslaan",
        NOT_CURRENT = "Niet de huidige blind",
        REROLL_USED = "In deze ante al opnieuw gerold",
    },

    PLAY = {
        PLAY_HAND   = "Hand spelen",
        DISCARD     = "Weggooien",
        SORT_RANK   = "Sorteren op waarde",
        SORT_SUIT   = "Sorteren op kleur",
        SORTED_RANK = "Gesorteerd op waarde",
        SORTED_SUIT = "Gesorteerd op kleur",
        NO_CARDS    = "Geen kaarten geselecteerd",
        NO_DISCARDS = "Geen weggooibeurten over",
        CANT_SELECT = "Kan niet selecteren",
        PICKED_UP   = "Opgepakt, {name}",
        PICKUP_CANCELLED = "Geannuleerd",
        SELECTION_CLEARED = "Selectie gewist",
        TUT_BLOCKED = "Volg de instructies van de tutorial om verder te gaan",
        MOVED       = "Verplaatst",
        PINNED_CANT_MOVE = "Vastgepind, kan niet verplaatsen",
        PLACE_LEFT    = "links van {name} neerleggen",
        PLACE_BETWEEN = "tussen {left} en {right} neerleggen",
        PLACE_RIGHT   = "rechts van {name} neerleggen",
        CANT_MOVE_HERE = "Kan hier niet neerleggen",
        USED        = "Gebruikt",
        CANT_USE    = "Nu niet bruikbaar",
        NEEDS_TARGETS = "Vereist geselecteerde handkaarten",
        SOLD        = "Verkocht",
        CANT_SELL   = "Niet verkoopbaar",
    },

    ROUND = {
        HAND_PLAYED = "Hand gespeeld, {count} handen over",
        DISCARDED   = "Weggegooid, {count} weggooibeurten over",
        HOOK_DISCARD   = "The Hook gooit {cards} weg",
        JOKER_DEBUFFED = "{name} verzwakt",
        OX    = "Geld op 0$ gezet",
        TOOTH = "{amount}$ verloren",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "gratis",
        SELL = "verkoop {cost}$",
        REROLL = "Opnieuw rollen, {cost}$",
        CANT_AFFORD = "Niet genoeg geld",
        NO_ROOM     = "Geen ruimte",
        BOUGHT      = "Gekocht",
        BOUGHT_USED = "Gekocht en gebruikt",
        REDEEMED    = "Ingewisseld",
        EMPTY       = "leeg",
    },

    CASHOUT = {
        LABEL         = "Uitbetalen",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Blindbeloning, {dollars}$",
        SAVED         = "Gered door Mr. Bones",
        HANDS_ROW     = "Resterende handen, {count}, {dollars}$",
        DISCARDS_ROW  = "Resterende weggooibeurten, {count}, {dollars}$",
        INTEREST_ROW  = "Rente, {dollars}$, {rate} per 5$ tot {max}",
        JOKER         = "Joker",
        TAG           = "Tag",
    },

    RUNINFO = {
        COL_LEVEL  = "level",
        COL_CHIPS  = "chips",
        COL_MULT   = "mult",
        COL_PLAYED = "gespeeld",
        COL_REQS   = "vereisten",
    },

    EVENTS = {
        DESTROYED = "{name} vernietigd",
        ADDED     = "{name} toegevoegd",
        HANDS     = "{amt} handen",
        DISCARDS  = "{amt} weggooibeurten",
        ANTE      = "{amt} ante",
        ROUND     = "{amt} ronde",
    },

    SCORING = {
        HAND    = "{name}, {chips} chips, {mult} mult",
        HAND_LEVEL = "{name} gestegen naar niveau {level}, {chips} chips, {mult} mult",
        HAND_LEVEL_DOWN = "{name} gezakt naar niveau {level}, {chips} chips, {mult} mult",
        CHIPS   = "{amt} chips",
        MULT    = "{amt} mult",
        XMULT   = "keer {amt} mult",
        ABBR_CHIPS = "c",
        ABBR_MULT  = "m",
        JOKER_POS = "joker op positie {n}",
        JOKER_POS_LIST = "geactiveerde jokerposities: {list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} verzwakt",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} chips keer {mult} mult is {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Score aankondigen",
        HAND_PREVIEW    = "Hand aankondigen tijdens selecteren",
        SCORING_DETAIL  = "Scoredetail",
        DETAIL_FULL     = "Volledig",
        DETAIL_JOKERS   = "Alleen jokers",
        DETAIL_SUMMARY  = "Samenvatting",
        ROUND_ACTIONS   = "Spelen en weggooien aankondigen",
        KEYBINDS        = "Toetsen",
        ANNOUNCEMENTS   = "Aankondigingen",
        TUTORIAL        = "Tutorial spelen",
        UNAVAILABLE     = "Blindfold-instellingen niet beschikbaar",
        PRESS_KEY       = "Druk op een toets of controllerknop voor {action}",
        BOUND           = "{action} toegewezen aan {key}",
        CANCELLED       = "Opnieuw toewijzen geannuleerd",
        CONFLICT        = "{key} is al toegewezen aan {action}, opnieuw toewijzen geannuleerd",
        CLICK_ORDER     = "Kaarten scoren in selectievolgorde",
        CURSOR_FOLLOW   = "Spelcursor volgt de navigatie",
        ANN_TYPE        = "Type aankondigen",
        ANN_SUBTYPE     = "Zeldzaamheid aankondigen",
        ANN_SELECTED    = "Selectie aankondigen",
        ANN_DESCRIPTION = "Beschrijvingen aankondigen",
        ANN_TOOLTIP     = "Tooltips aankondigen",
        ANN_EXTRAS      = "Optie-info aankondigen",
        ANN_POSITION    = "Positie aankondigen",
        ANN_CONTAINER   = "Gebied aankondigen",
        ANN_SCREEN      = "Schermwissels aankondigen",
        ANN_KEYWORDS    = "Trefwoordbeschrijvingen aankondigen",
        EV_TAGS         = "Tag-effecten aankondigen",
        EV_CARDS        = "Gemaakte en vernietigde kaarten aankondigen",
        EV_RESOURCES    = "Wijzigingen in hulpbronnen aankondigen",
        DISCORD         = "Bezoek de Discord",
        PATREON         = "Steun op Patreon",
        OPENING_DISCORD = "Discord wordt geopend in de browser.",
        OPENING_PATREON = "Patreon wordt geopend in de browser.",
        VIEW_DOCS       = "Documentatie bekijken",
        VIEW_CHANGES    = "Wijzigingen bekijken",
        OPENING_DOCS    = "Documentatie wordt geopend.",
        OPENING_CHANGES = "Wijzigingen worden geopend.",
        SPEECH_BACKEND  = "Spraak-backend",
        BACKEND_AUTO    = "Auto (beste beschikbaar)",
        SCORING         = "Score",
        FMT_CHIPS_GAIN  = "Aankondiging gewonnen chips",
        FMT_CHIPS_LOSS  = "Aankondiging verloren chips",
        FMT_MULT_GAIN   = "Aankondiging plus mult",
        FMT_MULT_LOSS   = "Aankondiging min mult",
        FMT_XMULT       = "Aankondiging keer mult",
    },
}
