-- loc/pl.lua — Polish. Machine translated (game-anchored terms); corrections
-- welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "przycisk",
        SLIDER   = "suwak",
        CYCLE    = "suwak",
        CHECKBOX = "pole wyboru",
        TAB      = "zakładka",
        CARD     = "karta",
        JOKER    = "joker",
        TAROT    = "tarot",
        PLANET   = "planeta",
        SPECTRAL = "widmowa",
        VOUCHER  = "kupon",
        BOOSTER  = "paczka wzmacniająca",
        TEXT_FIELD = "pole tekstowe",
    },
    STATUS = { ON = "włączone", OFF = "wyłączone" },
    LABELS = { LOCKED = "zablokowane", EMPTY = "puste", NOT_DISCOVERED = "Nieodkryte" },

    KEYS = {
        RETURN = "Enter", KPENTER = "Enter (klawiatura numeryczna)",
        LSHIFT = "Lewy Shift", RSHIFT = "Prawy Shift",
        LCTRL = "Lewy Ctrl", RCTRL = "Prawy Ctrl",
        LALT = "Lewy Alt", RALT = "Prawy Alt",
        UP = "Góra", DOWN = "Dół", LEFT = "Lewo", RIGHT = "Prawo",
        SPACE = "Spacja", ESCAPE = "Escape", TAB = "Tab", BACKSPACE = "Backspace",
        CTRL = "Ctrl", SHIFT = "Shift", ALT = "Alt",
        UNBOUND = "(nieprzypisane)",
    },

    PAD = {
        DPUP = "Krzyżak góra", DPDOWN = "Krzyżak dół",
        DPLEFT = "Krzyżak lewo", DPRIGHT = "Krzyżak prawo",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Lewy bumper", RIGHTSHOULDER = "Prawy bumper",
        LEFTSTICK = "Kliknięcie lewej gałki", RIGHTSTICK = "Kliknięcie prawej gałki",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Lewy spust", TRIGGERRIGHT = "Prawy spust",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Wczytano Blindfold {version}.",
        UPDATE_AVAILABLE = "Dostępna aktualizacja Blindfold: {current} do {latest}.",
        TUTORIAL_DONE = "Samouczek ukończony.",
    },
    RARITY = { COMMON = "pospolity", UNCOMMON = "niepospolity", RARE = "rzadki", LEGENDARY = "legendarny" },
    POSITION = { OF = "{index} z {total}" },

    SCREEN = {
        PLAYING      = "Gra",
        SHOP         = "Sklep",
        BLIND_SELECT = "Wybór przeszkadzajki",
        CASH_OUT     = "Wypłata",
        PACK         = "Paczka wzmacniająca",
        GAME_OVER    = "Koniec gry",
        MAIN_MENU    = "Menu główne",
        MENU         = "Menu",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Potwierdź odblokowanie wszystkiego",
        CONFIRM_ACTION = "Potwierdź {action}",
        COMPLETED      = "ukończone",
    },

    CONTAINER = {
        HAND        = "Ręka",
        JOKERS      = "Jokery",
        CONSUMABLES = "Przedmioty jednorazowe",
        VOUCHERS    = "Kupony",
        PACKS       = "Paczki",
        DECK        = "Talia",
        PLAYED      = "Zagrane",
        SHOP        = "Sklep",
        SHOP_GOODS  = "Kupony i paczki",
        PACK        = "Paczka",
    },

    PACK = {
        CHOOSE    = "Wybierz {choices} z {count}",
        CANT_SKIP = "Nie można pominąć",
    },

    CARD = {
        PLAYING    = "{rank} {suit}",
        DEBUFFED   = "osłabiona",
        FACE_DOWN  = "zakryta",
        TELL_SMALL    = "mała karta",
        TELL_SQUARE   = "kwadratowa karta",
        TELL_HALF     = "karta o połowie wysokości",
        TELL_SHORT    = "niska karta",
        TELL_RED_BACK = "czerwony rewers",
        SELL       = "sprzedaż {amount}$",
        CANT_SELL  = "nie można sprzedać",
        PINNED     = "przyszpilony",
        NEW        = "nowe",
        FORCED     = "wymuszona",
        WIN_STICKER = "naklejka {stake}",
        SELECTED   = "zaznaczona",
        DESELECTED = "odznaczona",
        TIP        = "{name}, {desc}",
        RANDOM_MULT = "+{min} do +{max} {mult}, losowo",
        SEL_POS    = "wybór {index}",
    },
    EDITION = {
        foil = "folia", holographic = "holograficzna",
        polychrome = "polichromia", negative = "negatyw",
    },
    SEAL = { GOLD = "złota pieczęć", RED = "czerwona pieczęć", BLUE = "niebieska pieczęć", PURPLE = "fioletowa pieczęć" },

    INPUT = {
        NAV_UP = "Nawiguj w górę", NAV_DOWN = "Nawiguj w dół",
        NAV_LEFT = "Nawiguj w lewo", NAV_RIGHT = "Nawiguj w prawo",
        ROW_START = "Początek rzędu", ROW_END = "Koniec rzędu",
        SELECT = "Wybierz / Aktywuj", GRAB = "Podnieś / Połóż",
        BACK = "Wstecz / Odznacz", PAUSE = "Pauza",
        PLAY_HAND = "Zagraj rękę", DISCARD = "Odrzuć",
        SELL = "Sprzedaj", USE = "Użyj",
        TAB_LEFT = "Poprzednia zakładka", TAB_RIGHT = "Następna zakładka",
        VIEW_DECK = "Zobacz talię",
        RUN_INFO = "Informacje o podejściu", DEBUG_DUMP = "Debug: zrzut fokusu",
        BUFFER_NEXT_ITEM = "Bufor: następny element", BUFFER_PREV_ITEM = "Bufor: poprzedni element",
        BUFFER_NEXT = "Bufor: następny bufor", BUFFER_PREV = "Bufor: poprzedni bufor",
        INFO_HANDS = "Odczytaj: pozostałe ręce", INFO_DISCARDS = "Odczytaj: pozostałe odrzucenia",
        INFO_SCORE = "Odczytaj: wynik i cel", INFO_JOKERS = "Odczytaj: miejsca na jokery",
        INFO_MONEY = "Odczytaj: pieniądze",
    },

    BUFFER = {
        EVENTS = "Zdarzenia",
        GAME = "Gra",
        CARD = "Karta",
        JOKER = "Joker",
        CONSUMABLE = "Przedmiot jednorazowy",
        CASHOUT = "Wypłata",
        UI = "Interfejs",
        NONE = "Brak buforów",
        EMPTY = "Bufor {buffer} jest pusty",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "Pozostałe ręce: {count}",
        DISCARDS = "Pozostałe odrzucenia: {count}",
        MONEY    = "{amount}$",
        SCORE    = "{score} z {req}",
        BLIND    = "Przeszkadzajka, {name}",
        ANTE     = "Wejście, {ante} z 8",
        ROUND    = "Runda, {round}",
        JOKERS   = "{count} z {slots} jokerów",
        NOT_NOW  = "Obecnie niedostępne",
    },

    STATS = {
        USES = "użyć: {count}",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, baza {base}, efektywnie {effective}",
        DRAWN     = "dobrana",
        FLIPPED   = "{count} dobranych zakrytych",
    },

    BLIND = {
        REQUIREMENT = "zdobądź co najmniej {amount}",
        REWARD      = "nagroda {dollars}$",
        SKIP        = "pomiń",
        NOT_CURRENT = "To nie jest obecna przeszkadzajka",
        REROLL_USED = "W tym wejściu już przelosowano",
    },

    PLAY = {
        PLAY_HAND   = "Zagraj rękę",
        DISCARD     = "Odrzuć",
        SORT_RANK   = "Sortuj według figur",
        SORT_SUIT   = "Sortuj według kolorów",
        SORTED_RANK = "Posortowano według figur",
        SORTED_SUIT = "Posortowano według kolorów",
        NO_CARDS    = "Nie zaznaczono kart",
        NO_DISCARDS = "Brak pozostałych odrzuceń",
        CANT_SELECT = "Nie można zaznaczyć",
        PICKED_UP   = "Podniesiono, {name}",
        PICKUP_CANCELLED = "Anulowano",
        SELECTION_CLEARED = "Zaznaczenie wyczyszczone",
        TUT_BLOCKED = "Postępuj zgodnie z instrukcjami samouczka, aby kontynuować",
        MOVED       = "Przeniesiono",
        PINNED_CANT_MOVE = "Przyszpilony, nie można przenieść",
        PLACE_LEFT    = "połóż na lewo od {name}",
        PLACE_BETWEEN = "połóż między {left} a {right}",
        PLACE_RIGHT   = "połóż na prawo od {name}",
        CANT_MOVE_HERE = "Nie można tu położyć",
        USED        = "Użyto",
        CANT_USE    = "Teraz nie można użyć",
        NEEDS_TARGETS = "Wymaga zaznaczonych kart w ręce",
        SOLD        = "Sprzedano",
        CANT_SELL   = "Nie można sprzedać",
    },

    ROUND = {
        HAND_PLAYED = "Zagrano rękę, pozostało rąk: {count}",
        DISCARDED   = "Odrzucono, pozostało odrzuceń: {count}",
        HOOK_DISCARD   = "The Hook odrzuca {cards}",
        JOKER_DEBUFFED = "{name} osłabiony",
        OX    = "Pieniądze wyzerowane",
        TOOTH = "Stracono {amount}$",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "za darmo",
        SELL = "sprzedaż {cost}$",
        REROLL = "Przelosuj, {cost}$",
        CANT_AFFORD = "Brak pieniędzy",
        NO_ROOM     = "Brak miejsca",
        BOUGHT      = "Kupiono",
        BOUGHT_USED = "Kupiono i użyto",
        REDEEMED    = "Wykorzystano",
        EMPTY       = "puste",
    },

    CASHOUT = {
        LABEL         = "Wypłata",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Nagroda za przeszkadzajkę, {dollars}$",
        SAVED         = "Uratowany przez Mr. Bonesa",
        HANDS_ROW     = "Pozostałe ręce, {count}, {dollars}$",
        DISCARDS_ROW  = "Pozostałe odrzucenia, {count}, {dollars}$",
        INTEREST_ROW  = "Odsetki, {dollars}$, {rate} za każde 5$ do {max}",
        JOKER         = "Joker",
        TAG           = "Znacznik",
    },

    RUNINFO = {
        COL_LEVEL  = "poziom",
        COL_CHIPS  = "żetony",
        COL_MULT   = "mnożnik",
        COL_PLAYED = "zagrane",
        COL_REQS   = "wymagania",
    },

    EVENTS = {
        DESTROYED = "{name} zniszczona",
        ADDED     = "{name} dodana",
        HANDS     = "{amt} ręce",
        DISCARDS  = "{amt} odrzucenia",
        ANTE      = "{amt} ante",
        ROUND     = "{amt} runda",
    },

    SCORING = {
        HAND    = "{name}, {chips} żetonów, {mult} mnożnika",
        HAND_LEVEL = "{name} awansowała na poziom {level}, {chips} żetonów, {mult} mnożnika",
        HAND_LEVEL_DOWN = "{name} spadła na poziom {level}, {chips} żetonów, {mult} mnożnika",
        CHIPS   = "{amt} żetonów",
        MULT    = "{amt} mnożnika",
        XMULT   = "razy {amt} mnożnika",
        ABBR_CHIPS = "ż",
        ABBR_MULT  = "m",
        JOKER_POS = "joker na pozycji {n}",
        JOKER_POS_LIST = "pozycje aktywowanych jokerów: {list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} osłabiony",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} żetonów razy {mult} mnożnika daje {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Ogłaszaj punktację",
        HAND_PREVIEW    = "Ogłaszaj rękę podczas zaznaczania",
        SCORING_DETAIL  = "Szczegółowość punktacji",
        DETAIL_FULL     = "Pełna",
        DETAIL_JOKERS   = "Tylko jokery",
        DETAIL_SUMMARY  = "Podsumowanie",
        ROUND_ACTIONS   = "Ogłaszaj zagrania i odrzucenia",
        KEYBINDS        = "Sterowanie",
        ANNOUNCEMENTS   = "Ogłoszenia",
        TUTORIAL        = "Zagraj w samouczek",
        UNAVAILABLE     = "Ustawienia Blindfold niedostępne",
        PRESS_KEY       = "Naciśnij klawisz lub przycisk kontrolera dla {action}",
        BOUND           = "{action} przypisano do {key}",
        CANCELLED       = "Anulowano zmianę przypisania",
        CONFLICT        = "{key} jest już przypisany do {action}, anulowano zmianę przypisania",
        CLICK_ORDER     = "Punktuj karty w kolejności wyboru",
        CURSOR_FOLLOW   = "Kursor gry podąża za nawigacją",
        ANN_TYPE        = "Ogłaszaj typ",
        ANN_SUBTYPE     = "Ogłaszaj rzadkość",
        ANN_SELECTED    = "Ogłaszaj zaznaczenie",
        ANN_DESCRIPTION = "Ogłaszaj opisy",
        ANN_TOOLTIP     = "Ogłaszaj podpowiedzi",
        ANN_EXTRAS      = "Ogłaszaj informacje o opcjach",
        ANN_POSITION    = "Ogłaszaj pozycję",
        ANN_CONTAINER   = "Ogłaszaj obszar",
        ANN_SCREEN      = "Ogłaszaj zmiany ekranu",
        ANN_KEYWORDS    = "Ogłaszaj opisy słów kluczowych",
        EV_TAGS         = "Ogłaszaj efekty tagów",
        EV_CARDS        = "Ogłaszaj utworzone i zniszczone karty",
        EV_RESOURCES    = "Ogłaszaj zmiany zasobów",
        DISCORD         = "Odwiedź Discorda",
        PATREON         = "Wesprzyj na Patreonie",
        OPENING_DISCORD = "Otwieranie Discorda w przeglądarce.",
        OPENING_PATREON = "Otwieranie Patreona w przeglądarce.",
        VIEW_DOCS       = "Zobacz dokumentację",
        VIEW_CHANGES    = "Zobacz zmiany",
        OPENING_DOCS    = "Otwieranie dokumentacji.",
        OPENING_CHANGES = "Otwieranie zmian.",
        SPEECH_BACKEND  = "Silnik mowy",
        BACKEND_AUTO    = "Auto (najlepszy dostępny)",
        SCORING         = "Punktacja",
        FMT_CHIPS_GAIN  = "Ogłaszanie zdobytych żetonów",
        FMT_CHIPS_LOSS  = "Ogłaszanie utraconych żetonów",
        FMT_MULT_GAIN   = "Ogłaszanie dodanego mnożnika",
        FMT_MULT_LOSS   = "Ogłaszanie odjętego mnożnika",
        FMT_XMULT       = "Ogłaszanie pomnożonego mnożnika",
    },
}
