-- loc/pt_br.lua — Brazilian Portuguese. Machine translated (game-anchored
-- terms); corrections welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "botão",
        SLIDER   = "controle deslizante",
        CYCLE    = "controle deslizante",
        CHECKBOX = "caixa de seleção",
        TAB      = "aba",
        CARD     = "carta",
        JOKER    = "curinga",
        TAROT    = "tarô",
        PLANET   = "planeta",
        SPECTRAL = "espectral",
        VOUCHER  = "cupom",
        BOOSTER  = "pacote de reforço",
        TEXT_FIELD = "campo de texto",
    },
    STATUS = { ON = "ativado", OFF = "desativado" },
    LABELS = { LOCKED = "bloqueado", EMPTY = "vazio", NOT_DISCOVERED = "Não descoberto" },

    KEYS = {
        RETURN = "Enter", KPENTER = "Enter (teclado numérico)",
        LSHIFT = "Shift esquerdo", RSHIFT = "Shift direito",
        LCTRL = "Ctrl esquerdo", RCTRL = "Ctrl direito",
        LALT = "Alt esquerdo", RALT = "Alt direito",
        UP = "Cima", DOWN = "Baixo", LEFT = "Esquerda", RIGHT = "Direita",
        SPACE = "Espaço", ESCAPE = "Esc", TAB = "Tab", BACKSPACE = "Backspace",
        CTRL = "Ctrl", SHIFT = "Shift", ALT = "Alt",
        UNBOUND = "(sem atribuição)",
    },

    PAD = {
        DPUP = "Direcional cima", DPDOWN = "Direcional baixo",
        DPLEFT = "Direcional esquerda", DPRIGHT = "Direcional direita",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Bumper esquerdo", RIGHTSHOULDER = "Bumper direito",
        LEFTSTICK = "Clique do analógico esquerdo", RIGHTSTICK = "Clique do analógico direito",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Gatilho esquerdo", TRIGGERRIGHT = "Gatilho direito",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold {version} carregado.",
        UPDATE_AVAILABLE = "Atualização do Blindfold disponível: {current} para {latest}.",
        TUTORIAL_DONE = "Tutorial concluído.",
    },
    RARITY = { COMMON = "comum", UNCOMMON = "incomum", RARE = "raro", LEGENDARY = "lendário" },
    POSITION = { OF = "{index} de {total}" },

    SCREEN = {
        PLAYING      = "Partida",
        SHOP         = "Loja",
        BLIND_SELECT = "Escolha do blind",
        CASH_OUT     = "Pagamento",
        PACK         = "Pacote de reforço",
        GAME_OVER    = "Fim de jogo",
        MAIN_MENU    = "Menu principal",
        MENU         = "Menu",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Confirmar desbloquear tudo",
        CONFIRM_ACTION = "Confirmar {action}",
        COMPLETED      = "concluído",
    },

    CONTAINER = {
        HAND        = "Mão",
        JOKERS      = "Curingas",
        CONSUMABLES = "Consumíveis",
        VOUCHERS    = "Cupons",
        PACKS       = "Pacotes",
        DECK        = "Baralho",
        PLAYED      = "Jogadas",
        SHOP        = "Loja",
        SHOP_GOODS  = "Cupons e pacotes",
        PACK        = "Pacote",
    },

    PACK = {
        CHOOSE    = "Escolha {choices} de {count}",
        CANT_SKIP = "Não é possível pular",
    },

    CARD = {
        PLAYING    = "{rank} de {suit}",
        DEBUFFED   = "enfraquecida",
        FACE_DOWN  = "virada para baixo",
        TELL_SMALL    = "carta pequena",
        TELL_SQUARE   = "carta quadrada",
        TELL_HALF     = "carta de meia altura",
        TELL_SHORT    = "carta curta",
        TELL_RED_BACK = "verso vermelho",
        SELL       = "venda {amount}$",
        CANT_SELL  = "não pode ser vendida",
        PINNED     = "encurralado",
        NEW        = "novo",
        FORCED     = "forçada",
        WIN_STICKER = "adesivo de {stake}",
        SELECTED   = "selecionada",
        DESELECTED = "desmarcada",
        TIP        = "{name}, {desc}",
        RANDOM_MULT = "+{min} a +{max} {mult}, aleatório",
        SEL_POS    = "seleção {index}",
    },
    EDITION = {
        foil = "laminada", holographic = "holográfica",
        polychrome = "policromática", negative = "negativa",
    },
    SEAL = { GOLD = "selo dourado", RED = "selo vermelho", BLUE = "selo azul", PURPLE = "selo roxo" },

    INPUT = {
        NAV_UP = "Navegar para cima", NAV_DOWN = "Navegar para baixo",
        NAV_LEFT = "Navegar para a esquerda", NAV_RIGHT = "Navegar para a direita",
        ROW_START = "Início da fileira", ROW_END = "Fim da fileira",
        SELECT = "Selecionar / Ativar", GRAB = "Pegar / Colocar",
        BACK = "Voltar / Desmarcar", PAUSE = "Pausa",
        PLAY_HAND = "Jogar mão", DISCARD = "Descartar",
        SELL = "Vender", USE = "Usar",
        TAB_LEFT = "Aba anterior", TAB_RIGHT = "Próxima aba",
        VIEW_DECK = "Ver baralho",
        RUN_INFO = "Informações da partida", DEBUG_DUMP = "Debug: despejar foco",
        BUFFER_NEXT_ITEM = "Buffer: próximo item", BUFFER_PREV_ITEM = "Buffer: item anterior",
        BUFFER_NEXT = "Buffer: próximo buffer", BUFFER_PREV = "Buffer: buffer anterior",
        INFO_HANDS = "Ler: mãos restantes", INFO_DISCARDS = "Ler: descartes restantes",
        INFO_SCORE = "Ler: pontuação e meta", INFO_JOKERS = "Ler: espaços de curinga",
        INFO_MONEY = "Ler: dinheiro",
    },

    BUFFER = {
        EVENTS = "Eventos",
        GAME = "Partida",
        CARD = "Carta",
        JOKER = "Curinga",
        CONSUMABLE = "Consumível",
        CASHOUT = "Pagamento",
        UI = "Interface",
        NONE = "Nenhum buffer",
        EMPTY = "O buffer {buffer} está vazio",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "{count} mãos restantes",
        DISCARDS = "{count} descartes restantes",
        MONEY    = "{amount}$",
        SCORE    = "{score} de {req}",
        BLIND    = "Blind, {name}",
        ANTE     = "Aposta, {ante} de 8",
        ROUND    = "Rodada, {round}",
        JOKERS   = "{count} de {slots} curingas",
        NOT_NOW  = "Indisponível no momento",
    },

    STATS = {
        USES = "{count} usos",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, base {base}, efetivo {effective}",
        DRAWN     = "comprada",
        FLIPPED   = "{count} compradas viradas para baixo",
    },

    BLIND = {
        REQUIREMENT = "marque pelo menos {amount}",
        REWARD      = "recompensa {dollars}$",
        SKIP        = "pular",
        NOT_CURRENT = "Não é o blind atual",
        REROLL_USED = "Já rolou de novo nesta aposta",
    },

    PLAY = {
        PLAY_HAND   = "Jogar mão",
        DISCARD     = "Descartar",
        SORT_RANK   = "Ordenar por valor",
        SORT_SUIT   = "Ordenar por naipe",
        SORTED_RANK = "Ordenado por valor",
        SORTED_SUIT = "Ordenado por naipe",
        NO_CARDS    = "Nenhuma carta selecionada",
        NO_DISCARDS = "Nenhum descarte restante",
        CANT_SELECT = "Não é possível selecionar",
        PICKED_UP   = "Pegou, {name}",
        PICKUP_CANCELLED = "Cancelado",
        SELECTION_CLEARED = "Seleção desfeita",
        TUT_BLOCKED = "Siga as instruções do tutorial para continuar",
        MOVED       = "Movida",
        PINNED_CANT_MOVE = "Encurralado, não pode ser movido",
        PLACE_LEFT    = "colocar à esquerda de {name}",
        PLACE_BETWEEN = "colocar entre {left} e {right}",
        PLACE_RIGHT   = "colocar à direita de {name}",
        CANT_MOVE_HERE = "Não é possível colocar aqui",
        USED        = "Usada",
        CANT_USE    = "Não pode ser usada agora",
        NEEDS_TARGETS = "Requer cartas selecionadas na mão",
        SOLD        = "Vendida",
        CANT_SELL   = "Não pode ser vendida",
    },

    ROUND = {
        HAND_PLAYED = "Mão jogada, {count} mãos restantes",
        DISCARDED   = "Descartado, {count} descartes restantes",
        HOOK_DISCARD   = "The Hook descarta {cards}",
        JOKER_DEBUFFED = "{name} enfraquecido",
        OX    = "Dinheiro zerado",
        TOOTH = "{amount}$ perdidos",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "grátis",
        SELL = "venda {cost}$",
        REROLL = "Rolar de novo, {cost}$",
        CANT_AFFORD = "Dinheiro insuficiente",
        NO_ROOM     = "Sem espaço",
        BOUGHT      = "Comprado",
        BOUGHT_USED = "Comprado e usado",
        REDEEMED    = "Resgatado",
        EMPTY       = "vazio",
    },

    CASHOUT = {
        LABEL         = "Receber",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Recompensa do blind, {dollars}$",
        SAVED         = "Salvo pelo Mr. Bones",
        HANDS_ROW     = "Mãos restantes, {count}, {dollars}$",
        DISCARDS_ROW  = "Descartes restantes, {count}, {dollars}$",
        INTEREST_ROW  = "Juros, {dollars}$, {rate} a cada 5$ até {max}",
        JOKER         = "Curinga",
        TAG           = "Marca",
    },

    RUNINFO = {
        COL_LEVEL  = "nível",
        COL_CHIPS  = "fichas",
        COL_MULT   = "multi",
        COL_PLAYED = "jogadas",
        COL_REQS   = "requisitos",
    },

    EVENTS = {
        DESTROYED = "{name} destruída",
        ADDED     = "{name} adicionada",
        HANDS     = "{amt} mãos",
        DISCARDS  = "{amt} descartes",
        ANTE      = "{amt} ante",
        ROUND     = "{amt} rodada",
    },

    SCORING = {
        HAND    = "{name}, {chips} fichas, {mult} multi",
        HAND_LEVEL = "{name} subiu para o nível {level}, {chips} fichas, {mult} multi",
        HAND_LEVEL_DOWN = "{name} desceu para o nível {level}, {chips} fichas, {mult} multi",
        CHIPS   = "{amt} fichas",
        MULT    = "{amt} multi",
        XMULT   = "vezes {amt} multi",
        ABBR_CHIPS = "f",
        ABBR_MULT  = "m",
        JOKER_POS = "curinga na posição {n}",
        JOKER_POS_LIST = "posições de curingas ativados: {list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} enfraquecido",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} fichas vezes {mult} multi é igual a {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Anunciar pontuação",
        HAND_PREVIEW    = "Anunciar a mão ao selecionar",
        SCORING_DETAIL  = "Detalhe da pontuação",
        DETAIL_FULL     = "Completo",
        DETAIL_JOKERS   = "Somente curingas",
        DETAIL_SUMMARY  = "Resumo",
        ROUND_ACTIONS   = "Anunciar jogadas e descartes",
        KEYBINDS        = "Atalhos",
        ANNOUNCEMENTS   = "Anúncios",
        TUTORIAL        = "Jogar tutorial",
        UNAVAILABLE     = "Configurações do Blindfold indisponíveis",
        PRESS_KEY       = "Pressione uma tecla ou botão do controle para {action}",
        BOUND           = "{action} atribuído a {key}",
        CANCELLED       = "Reatribuição cancelada",
        CONFLICT        = "{key} já está atribuído a {action}, reatribuição cancelada",
        CLICK_ORDER     = "Pontuar cartas na ordem de seleção",
        CURSOR_FOLLOW   = "O cursor do jogo segue a navegação",
        ANN_TYPE        = "Anunciar tipo",
        ANN_SUBTYPE     = "Anunciar raridade",
        ANN_SELECTED    = "Anunciar seleção",
        ANN_DESCRIPTION = "Anunciar descrições",
        ANN_TOOLTIP     = "Anunciar dicas",
        ANN_EXTRAS      = "Anunciar informações de opções",
        ANN_POSITION    = "Anunciar posição",
        ANN_CONTAINER   = "Anunciar área",
        ANN_SCREEN      = "Anunciar mudanças de tela",
        ANN_KEYWORDS    = "Anunciar descrições de palavras-chave",
        EV_TAGS         = "Anunciar efeitos de etiquetas",
        EV_CARDS        = "Anunciar cartas criadas e destruídas",
        EV_RESOURCES    = "Anunciar mudanças de recursos",
        DISCORD         = "Visitar o Discord",
        PATREON         = "Apoie no Patreon",
        OPENING_DISCORD = "Abrindo o Discord no navegador.",
        OPENING_PATREON = "Abrindo o Patreon no navegador.",
        VIEW_DOCS       = "Ver documentação",
        VIEW_CHANGES    = "Ver alterações",
        OPENING_DOCS    = "Abrindo a documentação.",
        OPENING_CHANGES = "Abrindo as alterações.",
        SPEECH_BACKEND  = "Mecanismo de voz",
        BACKEND_AUTO    = "Auto (melhor disponível)",
        SCORING         = "Pontuação",
        FMT_CHIPS_GAIN  = "Anúncio de fichas ganhas",
        FMT_CHIPS_LOSS  = "Anúncio de fichas perdidas",
        FMT_MULT_GAIN   = "Anúncio de multi somado",
        FMT_MULT_LOSS   = "Anúncio de multi subtraído",
        FMT_XMULT       = "Anúncio de multi multiplicado",
    },
}
