-- loc/ru.lua — Russian. Machine translated (game-anchored terms); corrections
-- welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "кнопка",
        SLIDER   = "ползунок",
        CYCLE    = "ползунок",
        CHECKBOX = "флажок",
        TAB      = "вкладка",
        CARD     = "карта",
        JOKER    = "джокер",
        TAROT    = "таро",
        PLANET   = "планета",
        SPECTRAL = "спектральная",
        VOUCHER  = "ваучер",
        BOOSTER  = "бустерный набор",
        TEXT_FIELD = "текстовое поле",
    },
    STATUS = { ON = "включено", OFF = "выключено" },
    LABELS = { LOCKED = "заблокировано", EMPTY = "пусто", NOT_DISCOVERED = "Не обнаружено" },

    KEYS = {
        RETURN = "Enter", KPENTER = "Enter (цифровой блок)",
        LSHIFT = "Левый Shift", RSHIFT = "Правый Shift",
        LCTRL = "Левый Ctrl", RCTRL = "Правый Ctrl",
        LALT = "Левый Alt", RALT = "Правый Alt",
        UP = "Вверх", DOWN = "Вниз", LEFT = "Влево", RIGHT = "Вправо",
        SPACE = "Пробел", ESCAPE = "Escape", TAB = "Tab", BACKSPACE = "Backspace",
        CTRL = "Ctrl", SHIFT = "Shift", ALT = "Alt",
        UNBOUND = "(не назначено)",
    },

    PAD = {
        DPUP = "Крестовина вверх", DPDOWN = "Крестовина вниз",
        DPLEFT = "Крестовина влево", DPRIGHT = "Крестовина вправо",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "Левый бампер", RIGHTSHOULDER = "Правый бампер",
        LEFTSTICK = "Нажатие левого стика", RIGHTSTICK = "Нажатие правого стика",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "Левый триггер", TRIGGERRIGHT = "Правый триггер",
        CHORD = "{mod} + {button}",
    },

    MISC = {
        LOADED = "Blindfold {version} загружен.",
        UPDATE_AVAILABLE = "Доступно обновление Blindfold: {current} до {latest}.",
        TUTORIAL_DONE = "Обучение завершено.",
    },
    RARITY = { COMMON = "обычный", UNCOMMON = "необычный", RARE = "редкий", LEGENDARY = "легендарный" },
    POSITION = { OF = "{index} из {total}" },

    SCREEN = {
        PLAYING      = "Игра",
        SHOP         = "Магазин",
        BLIND_SELECT = "Выбор блайнда",
        CASH_OUT     = "Выплата",
        PACK         = "Бустерный набор",
        GAME_OVER    = "Игра окончена",
        MAIN_MENU    = "Главное меню",
        MENU         = "Меню",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "Подтвердить разблокировку всего",
        CONFIRM_ACTION = "Подтвердить: {action}",
        COMPLETED      = "пройдено",
    },

    CONTAINER = {
        HAND        = "Рука",
        JOKERS      = "Джокеры",
        CONSUMABLES = "Расходники",
        VOUCHERS    = "Ваучеры",
        PACKS       = "Наборы",
        DECK        = "Колода",
        PLAYED      = "Сыгранные",
        SHOP        = "Магазин",
        SHOP_GOODS  = "Ваучеры и наборы",
        PACK        = "Набор",
    },

    PACK = {
        CHOOSE    = "Выберите {choices} из {count}",
        CANT_SKIP = "Нельзя пропустить",
    },

    CARD = {
        PLAYING    = "{rank} {suit}",
        DEBUFFED   = "ослаблена",
        FACE_DOWN  = "рубашкой вверх",
        TELL_SMALL    = "маленькая карта",
        TELL_SQUARE   = "квадратная карта",
        TELL_HALF     = "карта в полвысоты",
        TELL_SHORT    = "укороченная карта",
        TELL_RED_BACK = "красная рубашка",
        SELL       = "продажа {amount}$",
        CANT_SELL  = "нельзя продать",
        PINNED     = "закреплено",
        NEW        = "новое",
        FORCED     = "принудительно",
        WIN_STICKER = "наклейка: {stake}",
        SELECTED   = "выбрана",
        DESELECTED = "снята",
        TIP        = "{name}, {desc}",
        RANDOM_MULT = "от +{min} до +{max} {mult}, случайно",
        SEL_POS    = "выбор {index}",
    },
    EDITION = {
        foil = "фольга", holographic = "голографическая",
        polychrome = "полихромная", negative = "негатив",
    },
    SEAL = { GOLD = "золотая печать", RED = "красная печать", BLUE = "синяя печать", PURPLE = "фиолетовая печать" },

    INPUT = {
        NAV_UP = "Вверх", NAV_DOWN = "Вниз",
        NAV_LEFT = "Влево", NAV_RIGHT = "Вправо",
        ROW_START = "Начало ряда", ROW_END = "Конец ряда",
        SELECT = "Выбрать / Активировать", GRAB = "Взять / Положить",
        BACK = "Назад / Снять выбор", PAUSE = "Пауза",
        PLAY_HAND = "Сыграть руку", DISCARD = "Сброс",
        SELL = "Продать", USE = "Использовать",
        TAB_LEFT = "Предыдущая вкладка", TAB_RIGHT = "Следующая вкладка",
        VIEW_DECK = "Просмотр колоды",
        RUN_INFO = "Информация о забеге", DEBUG_DUMP = "Отладка: дамп фокуса",
        BUFFER_NEXT_ITEM = "Буфер: следующий элемент", BUFFER_PREV_ITEM = "Буфер: предыдущий элемент",
        BUFFER_NEXT = "Буфер: следующий буфер", BUFFER_PREV = "Буфер: предыдущий буфер",
        INFO_HANDS = "Прочитать: оставшиеся руки", INFO_DISCARDS = "Прочитать: оставшиеся сбросы",
        INFO_SCORE = "Прочитать: счёт и цель", INFO_JOKERS = "Прочитать: слоты джокеров",
        INFO_MONEY = "Прочитать: деньги",
    },

    BUFFER = {
        EVENTS = "События",
        GAME = "Игра",
        CARD = "Карта",
        JOKER = "Джокер",
        CONSUMABLE = "Расходник",
        CASHOUT = "Выплата",
        UI = "Интерфейс",
        NONE = "Нет буферов",
        EMPTY = "Буфер {buffer} пуст",
        CURRENT = "{buffer}, {item}",
    },
    GAME = {
        HANDS    = "Осталось рук: {count}",
        DISCARDS = "Осталось сбросов: {count}",
        MONEY    = "{amount}$",
        SCORE    = "{score} из {req}",
        BLIND    = "Блайнд, {name}",
        ANTE     = "Анте, {ante} из 8",
        ROUND    = "Раунд, {round}",
        JOKERS   = "Джокеров: {count} из {slots}",
        NOT_NOW  = "Сейчас недоступно",
    },

    STATS = {
        USES = "использований: {count}",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}: {desc}",
        TALLY     = "{label}, {count}",
        TALLY_MOD = "{label}, база {base}, фактически {effective}",
        DRAWN     = "взята",
        FLIPPED   = "взято рубашкой вверх: {count}",
    },

    BLIND = {
        REQUIREMENT = "наберите не менее {amount}",
        REWARD      = "награда {dollars}$",
        SKIP        = "пропустить",
        NOT_CURRENT = "Не текущий блайнд",
        REROLL_USED = "В этом анте уже перебрасывали",
    },

    PLAY = {
        PLAY_HAND   = "Сыграть руку",
        DISCARD     = "Сброс",
        SORT_RANK   = "Сортировать по достоинству",
        SORT_SUIT   = "Сортировать по масти",
        SORTED_RANK = "Отсортировано по достоинству",
        SORTED_SUIT = "Отсортировано по масти",
        NO_CARDS    = "Карты не выбраны",
        NO_DISCARDS = "Сбросов не осталось",
        CANT_SELECT = "Нельзя выбрать",
        PICKED_UP   = "Взята, {name}",
        PICKUP_CANCELLED = "Отменено",
        SELECTION_CLEARED = "Выбор снят",
        TUT_BLOCKED = "Следуйте указаниям обучения, чтобы продолжить",
        MOVED       = "Перемещена",
        PINNED_CANT_MOVE = "Закреплено, нельзя переместить",
        PLACE_LEFT    = "положить слева от {name}",
        PLACE_BETWEEN = "положить между {left} и {right}",
        PLACE_RIGHT   = "положить справа от {name}",
        CANT_MOVE_HERE = "Сюда положить нельзя",
        USED        = "Использована",
        CANT_USE    = "Сейчас нельзя использовать",
        NEEDS_TARGETS = "Нужны выбранные карты в руке",
        SOLD        = "Продана",
        CANT_SELL   = "Нельзя продать",
    },

    ROUND = {
        HAND_PLAYED = "Рука сыграна, осталось рук: {count}",
        DISCARDED   = "Сброшено, осталось сбросов: {count}",
        HOOK_DISCARD   = "The Hook сбрасывает {cards}",
        JOKER_DEBUFFED = "{name} ослаблен",
        OX    = "Деньги обнулены",
        TOOTH = "Потеряно {amount}$",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "бесплатно",
        SELL = "продажа {cost}$",
        REROLL = "Переброс, {cost}$",
        CANT_AFFORD = "Не хватает денег",
        NO_ROOM     = "Нет места",
        BOUGHT      = "Куплено",
        BOUGHT_USED = "Куплено и использовано",
        REDEEMED    = "Активировано",
        EMPTY       = "пусто",
    },

    CASHOUT = {
        LABEL         = "Выплата",
        TOTAL         = "{dollars}$",
        ROW           = "{label}, {dollars}$",
        BLIND_ROW     = "Награда за блайнд, {dollars}$",
        SAVED         = "Спасён Mr. Bones",
        HANDS_ROW     = "Оставшиеся руки, {count}, {dollars}$",
        DISCARDS_ROW  = "Оставшиеся сбросы, {count}, {dollars}$",
        INTEREST_ROW  = "Проценты, {dollars}$, {rate} за каждые 5$ до {max}",
        JOKER         = "Джокер",
        TAG           = "Тег",
    },

    RUNINFO = {
        COL_LEVEL  = "уровень",
        COL_CHIPS  = "фишки",
        COL_MULT   = "множитель",
        COL_PLAYED = "сыграно",
        COL_REQS   = "требования",
    },

    EVENTS = {
        DESTROYED = "{name} уничтожена",
        ADDED     = "{name} добавлена",
        HANDS     = "{amt} руки",
        DISCARDS  = "{amt} сбросы",
        ANTE      = "{amt} анте",
        ROUND     = "{amt} раунд",
    },

    SCORING = {
        HAND    = "{name}, {chips} фишек, {mult} множитель",
        HAND_LEVEL = "{name}: уровень повышен до {level}, {chips} фишек, {mult} множитель",
        HAND_LEVEL_DOWN = "{name}: уровень понижен до {level}, {chips} фишек, {mult} множитель",
        CHIPS   = "{amt} фишек",
        MULT    = "{amt} множитель",
        XMULT   = "умножить на {amt}",
        ABBR_CHIPS = "ф",
        ABBR_MULT  = "м",
        JOKER_POS = "джокер на позиции {n}",
        JOKER_POS_LIST = "позиции сработавших джокеров: {list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source} ослаблен",
        SOURCE  = "{source}, {effect}",
        TOTAL   = "{chips} фишек умножить на {mult} равно {score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "Озвучивать подсчёт очков",
        HAND_PREVIEW    = "Озвучивать руку при выборе",
        SCORING_DETAIL  = "Детализация подсчёта",
        DETAIL_FULL     = "Полная",
        DETAIL_JOKERS   = "Только джокеры",
        DETAIL_SUMMARY  = "Сводка",
        ROUND_ACTIONS   = "Озвучивать игры и сбросы",
        KEYBINDS        = "Управление",
        ANNOUNCEMENTS   = "Озвучивание",
        TUTORIAL        = "Пройти обучение",
        UNAVAILABLE     = "Настройки Blindfold недоступны",
        PRESS_KEY       = "Нажмите клавишу или кнопку контроллера для {action}",
        BOUND           = "{action} назначено на {key}",
        CANCELLED       = "Переназначение отменено",
        CONFLICT        = "{key} уже назначено на {action}, переназначение отменено",
        CLICK_ORDER     = "Подсчёт карт в порядке выбора",
        CURSOR_FOLLOW   = "Курсор игры следует за навигацией",
        ANN_TYPE        = "Озвучивать тип",
        ANN_SUBTYPE     = "Озвучивать редкость",
        ANN_SELECTED    = "Озвучивать выбор",
        ANN_DESCRIPTION = "Озвучивать описания",
        ANN_TOOLTIP     = "Озвучивать подсказки",
        ANN_EXTRAS      = "Озвучивать сведения об опциях",
        ANN_POSITION    = "Озвучивать позицию",
        ANN_CONTAINER   = "Озвучивать область",
        ANN_SCREEN      = "Озвучивать смену экрана",
        ANN_KEYWORDS    = "Озвучивать описания ключевых слов",
        EV_TAGS         = "Озвучивать эффекты меток",
        EV_CARDS        = "Озвучивать созданные и уничтоженные карты",
        EV_RESOURCES    = "Озвучивать изменения ресурсов",
        DISCORD         = "Наш Discord",
        PATREON         = "Поддержать на Patreon",
        OPENING_DISCORD = "Discord открывается в браузере.",
        OPENING_PATREON = "Patreon открывается в браузере.",
        VIEW_DOCS       = "Открыть документацию",
        VIEW_CHANGES    = "Открыть список изменений",
        OPENING_DOCS    = "Открывается документация.",
        OPENING_CHANGES = "Открывается список изменений.",
        SPEECH_BACKEND  = "Речевой движок",
        BACKEND_AUTO    = "Авто (лучший доступный)",
        SCORING         = "Подсчёт очков",
        FMT_CHIPS_GAIN  = "Озвучивание полученных фишек",
        FMT_CHIPS_LOSS  = "Озвучивание потерянных фишек",
        FMT_MULT_GAIN   = "Озвучивание плюс-множителя",
        FMT_MULT_LOSS   = "Озвучивание минус-множителя",
        FMT_XMULT       = "Озвучивание умножения множителя",
    },
}
