-- loc/zh_cn.lua — Simplified Chinese. Machine translated (game-anchored
-- terms); corrections welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "按钮",
        SLIDER   = "滑块",
        CYCLE    = "滑块",
        CHECKBOX = "复选框",
        TAB      = "标签页",
        CARD     = "卡牌",
        JOKER    = "小丑牌",
        TAROT    = "塔罗牌",
        PLANET   = "星球牌",
        SPECTRAL = "幻灵牌",
        VOUCHER  = "优惠券",
        BOOSTER  = "补充包",
        TEXT_FIELD = "文本框",
    },
    STATUS = { ON = "开", OFF = "关" },
    LABELS = { LOCKED = "锁定", EMPTY = "空", NOT_DISCOVERED = "未发现" },

    KEYS = {
        RETURN = "回车", KPENTER = "小键盘回车",
        LSHIFT = "左Shift", RSHIFT = "右Shift",
        LCTRL = "左Ctrl", RCTRL = "右Ctrl",
        LALT = "左Alt", RALT = "右Alt",
        UP = "上", DOWN = "下", LEFT = "左", RIGHT = "右",
        SPACE = "空格", ESCAPE = "Esc", TAB = "Tab", BACKSPACE = "退格",
        CTRL = "Ctrl", SHIFT = "Shift", ALT = "Alt",
        UNBOUND = "（未绑定）",
    },

    PAD = {
        DPUP = "方向键上", DPDOWN = "方向键下",
        DPLEFT = "方向键左", DPRIGHT = "方向键右",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "左肩键", RIGHTSHOULDER = "右肩键",
        LEFTSTICK = "按下左摇杆", RIGHTSTICK = "按下右摇杆",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "左扳机", TRIGGERRIGHT = "右扳机",
        CHORD = "{mod}+{button}",
    },

    MISC = {
        LOADED = "Blindfold {version} 已加载。",
        UPDATE_AVAILABLE = "Blindfold有可用更新：{current}到{latest}。",
        TUTORIAL_DONE = "教程完成。",
    },
    RARITY = { COMMON = "普通", UNCOMMON = "罕见", RARE = "稀有", LEGENDARY = "传奇" },
    POSITION = { OF = "第{index}个，共{total}个" },

    SCREEN = {
        PLAYING      = "游戏中",
        SHOP         = "商店",
        BLIND_SELECT = "选择盲注",
        CASH_OUT     = "结算",
        PACK         = "补充包",
        GAME_OVER    = "游戏结束",
        MAIN_MENU    = "主菜单",
        MENU         = "菜单",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "确认全部解锁",
        CONFIRM_ACTION = "确认{action}",
        COMPLETED      = "已完成",
    },

    CONTAINER = {
        HAND        = "手牌",
        JOKERS      = "小丑牌",
        CONSUMABLES = "消耗牌",
        VOUCHERS    = "优惠券",
        PACKS       = "补充包",
        DECK        = "牌组",
        PLAYED      = "已打出",
        SHOP        = "商店",
        SHOP_GOODS  = "优惠券和补充包",
        PACK        = "补充包",
    },

    PACK = {
        CHOOSE    = "从{count}张中选择{choices}张",
        CANT_SKIP = "无法跳过",
    },

    CARD = {
        PLAYING    = "{suit}{rank}",
        DEBUFFED   = "被削弱",
        FACE_DOWN  = "背面朝上",
        TELL_SMALL    = "小尺寸卡牌",
        TELL_SQUARE   = "正方形卡牌",
        TELL_HALF     = "半高卡牌",
        TELL_SHORT    = "矮卡牌",
        TELL_RED_BACK = "红色牌背",
        SELL       = "售价{amount}$",
        CANT_SELL  = "无法出售",
        PINNED     = "已固定",
        NEW        = "新",
        FORCED     = "强制选中",
        WIN_STICKER = "{stake}贴纸",
        SELECTED   = "已选中",
        DESELECTED = "已取消选中",
        TIP        = "{name}，{desc}",
        RANDOM_MULT = "+{min}至+{max}{mult}，随机",
        SEL_POS    = "选择{index}",
    },
    EDITION = {
        foil = "闪箔", holographic = "镭射",
        polychrome = "多彩", negative = "负片",
    },
    SEAL = { GOLD = "金蜡封", RED = "红蜡封", BLUE = "蓝蜡封", PURPLE = "紫蜡封" },

    INPUT = {
        NAV_UP = "向上导航", NAV_DOWN = "向下导航",
        NAV_LEFT = "向左导航", NAV_RIGHT = "向右导航",
        ROW_START = "行首", ROW_END = "行尾",
        SELECT = "选择／激活", GRAB = "拿起／放下",
        BACK = "返回／取消选择", PAUSE = "暂停",
        PLAY_HAND = "出牌", DISCARD = "弃牌",
        SELL = "出售", USE = "使用",
        TAB_LEFT = "上一个标签页", TAB_RIGHT = "下一个标签页",
        VIEW_DECK = "查看牌组",
        RUN_INFO = "游戏信息", DEBUG_DUMP = "调试：输出焦点",
        BUFFER_NEXT_ITEM = "缓冲区：下一项", BUFFER_PREV_ITEM = "缓冲区：上一项",
        BUFFER_NEXT = "缓冲区：下一个缓冲区", BUFFER_PREV = "缓冲区：上一个缓冲区",
        INFO_HANDS = "朗读：剩余出牌次数", INFO_DISCARDS = "朗读：剩余弃牌次数",
        INFO_SCORE = "朗读：分数与目标", INFO_JOKERS = "朗读：小丑牌栏位",
        INFO_MONEY = "朗读：资金",
    },

    BUFFER = {
        EVENTS = "事件",
        GAME = "游戏",
        CARD = "卡牌",
        JOKER = "小丑牌",
        CONSUMABLE = "消耗牌",
        CASHOUT = "结算",
        UI = "界面",
        NONE = "没有缓冲区",
        EMPTY = "{buffer}缓冲区为空",
        CURRENT = "{buffer}，{item}",
    },
    GAME = {
        HANDS    = "剩余出牌次数{count}",
        DISCARDS = "剩余弃牌次数{count}",
        MONEY    = "{amount}$",
        SCORE    = "{score}，目标{req}",
        BLIND    = "盲注，{name}",
        ANTE     = "底注，第{ante}关，共8关",
        ROUND    = "回合，{round}",
        JOKERS   = "小丑牌{count}张，共{slots}栏",
        NOT_NOW  = "当前不可用",
    },

    STATS = {
        USES = "使用{count}次",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}：{desc}",
        TALLY     = "{label}，{count}",
        TALLY_MOD = "{label}，基础{base}，实际{effective}",
        DRAWN     = "已抽出",
        FLIPPED   = "{count}张背面朝上抽出",
    },

    BLIND = {
        REQUIREMENT = "至少得到{amount}分",
        REWARD      = "奖励{dollars}$",
        SKIP        = "跳过",
        NOT_CURRENT = "不是当前盲注",
        REROLL_USED = "本底注已重掷过",
    },

    PLAY = {
        PLAY_HAND   = "出牌",
        DISCARD     = "弃牌",
        SORT_RANK   = "按点数排序",
        SORT_SUIT   = "按花色排序",
        SORTED_RANK = "已按点数排序",
        SORTED_SUIT = "已按花色排序",
        NO_CARDS    = "没有选中卡牌",
        NO_DISCARDS = "没有剩余弃牌次数",
        CANT_SELECT = "无法选择",
        PICKED_UP   = "已拿起，{name}",
        PICKUP_CANCELLED = "已取消",
        SELECTION_CLEARED = "已取消选择",
        TUT_BLOCKED = "请按照教程指示继续",
        MOVED       = "已移动",
        PINNED_CANT_MOVE = "已固定，无法移动",
        PLACE_LEFT    = "放到{name}左边",
        PLACE_BETWEEN = "放到{left}和{right}之间",
        PLACE_RIGHT   = "放到{name}右边",
        CANT_MOVE_HERE = "无法放到这里",
        USED        = "已使用",
        CANT_USE    = "现在无法使用",
        NEEDS_TARGETS = "需要先选中手牌",
        SOLD        = "已出售",
        CANT_SELL   = "无法出售",
    },

    ROUND = {
        HAND_PLAYED = "已出牌，剩余{count}次",
        DISCARDED   = "已弃牌，剩余{count}次",
        HOOK_DISCARD   = "The Hook弃掉了{cards}",
        JOKER_DEBUFFED = "{name}被削弱",
        OX    = "资金归零",
        TOOTH = "失去{amount}$",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "免费",
        SELL = "售价{cost}$",
        REROLL = "重掷，{cost}$",
        CANT_AFFORD = "资金不足",
        NO_ROOM     = "没有空位",
        BOUGHT      = "已购买",
        BOUGHT_USED = "已购买并使用",
        REDEEMED    = "已兑换",
        EMPTY       = "空",
    },

    CASHOUT = {
        LABEL         = "结算",
        TOTAL         = "{dollars}$",
        ROW           = "{label}，{dollars}$",
        BLIND_ROW     = "盲注奖励，{dollars}$",
        SAVED         = "被Mr. Bones救了一命",
        HANDS_ROW     = "剩余出牌次数，{count}，{dollars}$",
        DISCARDS_ROW  = "剩余弃牌次数，{count}，{dollars}$",
        INTEREST_ROW  = "利息，{dollars}$，每5$获得{rate}，上限{max}",
        JOKER         = "小丑牌",
        TAG           = "标签",
    },

    RUNINFO = {
        COL_LEVEL  = "等级",
        COL_CHIPS  = "筹码",
        COL_MULT   = "倍率",
        COL_PLAYED = "打出次数",
        COL_REQS   = "要求",
    },

    EVENTS = {
        DESTROYED = "{name}被摧毁",
        ADDED     = "{name}已添加",
        HANDS     = "出牌次数{amt}",
        DISCARDS  = "弃牌次数{amt}",
        ANTE      = "底注{amt}",
        ROUND     = "回合{amt}",
    },

    SCORING = {
        HAND    = "{name}，{chips}筹码，{mult}倍率",
        HAND_LEVEL = "{name}升到{level}级，{chips}筹码，{mult}倍率",
        HAND_LEVEL_DOWN = "{name}降到{level}级，{chips}筹码，{mult}倍率",
        CHIPS   = "{amt}筹码",
        MULT    = "{amt}倍率",
        XMULT   = "乘{amt}倍率",
        ABBR_CHIPS = "筹",
        ABBR_MULT  = "倍率",
        JOKER_POS = "位置{n}的小丑牌",
        JOKER_POS_LIST = "触发的小丑牌位置：{list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source}被削弱",
        SOURCE  = "{source}，{effect}",
        TOTAL   = "{chips}筹码乘{mult}倍率等于{score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "朗读计分",
        HAND_PREVIEW    = "选牌时朗读牌型",
        SCORING_DETAIL  = "计分详细程度",
        DETAIL_FULL     = "完整",
        DETAIL_JOKERS   = "仅小丑牌",
        DETAIL_SUMMARY  = "摘要",
        ROUND_ACTIONS   = "朗读出牌和弃牌",
        KEYBINDS        = "按键设置",
        ANNOUNCEMENTS   = "朗读设置",
        TUTORIAL        = "游玩教程",
        UNAVAILABLE     = "Blindfold设置不可用",
        PRESS_KEY       = "请按下要分配给{action}的按键或手柄按钮",
        BOUND           = "{action}已绑定到{key}",
        CANCELLED       = "已取消重新绑定",
        CONFLICT        = "{key}已绑定到{action}，已取消重新绑定",
        CLICK_ORDER     = "按选择顺序计分卡牌",
        CURSOR_FOLLOW   = "游戏光标跟随导航",
        ANN_TYPE        = "朗读类型",
        ANN_SUBTYPE     = "朗读稀有度",
        ANN_SELECTED    = "朗读选中状态",
        ANN_DESCRIPTION = "朗读描述",
        ANN_TOOLTIP     = "朗读提示",
        ANN_EXTRAS      = "朗读选项信息",
        ANN_POSITION    = "朗读位置",
        ANN_CONTAINER   = "朗读区域",
        ANN_SCREEN      = "朗读画面切换",
        ANN_KEYWORDS    = "朗读关键词说明",
        EV_TAGS         = "播报标签效果",
        EV_CARDS        = "播报创建和摧毁的卡牌",
        EV_RESOURCES    = "播报资源变化",
        DISCORD         = "访问Discord",
        PATREON         = "在Patreon上支持我们",
        OPENING_DISCORD = "正在浏览器中打开Discord。",
        OPENING_PATREON = "正在浏览器中打开Patreon。",
        VIEW_DOCS       = "查看文档",
        VIEW_CHANGES    = "查看更新内容",
        OPENING_DOCS    = "正在打开文档。",
        OPENING_CHANGES = "正在打开更新内容。",
        SPEECH_BACKEND  = "语音后端",
        BACKEND_AUTO    = "自动（最佳可用）",
        SCORING         = "计分",
        FMT_CHIPS_GAIN  = "获得筹码播报",
        FMT_CHIPS_LOSS  = "失去筹码播报",
        FMT_MULT_GAIN   = "加倍率播报",
        FMT_MULT_LOSS   = "减倍率播报",
        FMT_XMULT       = "乘倍率播报",
    },
}
