-- loc/zh_tw.lua — Traditional Chinese. Machine translated (game-anchored
-- terms); corrections welcome. Keys omitted here fall back to English.
local require = ...

return {
    TYPES = {
        BUTTON   = "按鈕",
        SLIDER   = "滑桿",
        CYCLE    = "滑桿",
        CHECKBOX = "核取方塊",
        TAB      = "分頁",
        CARD     = "卡牌",
        JOKER    = "小丑牌",
        TAROT    = "塔羅牌",
        PLANET   = "星球牌",
        SPECTRAL = "幻靈牌",
        VOUCHER  = "禮券",
        BOOSTER  = "擴充包",
        TEXT_FIELD = "文字輸入欄",
    },
    STATUS = { ON = "開", OFF = "關" },
    LABELS = { LOCKED = "已鎖定", EMPTY = "空", NOT_DISCOVERED = "未發現" },

    KEYS = {
        RETURN = "Enter", KPENTER = "數字鍵盤Enter",
        LSHIFT = "左Shift", RSHIFT = "右Shift",
        LCTRL = "左Ctrl", RCTRL = "右Ctrl",
        LALT = "左Alt", RALT = "右Alt",
        UP = "上", DOWN = "下", LEFT = "左", RIGHT = "右",
        SPACE = "空白鍵", ESCAPE = "Esc", TAB = "Tab", BACKSPACE = "退格鍵",
        CTRL = "Ctrl", SHIFT = "Shift", ALT = "Alt",
        UNBOUND = "（未綁定）",
    },

    PAD = {
        DPUP = "方向鍵上", DPDOWN = "方向鍵下",
        DPLEFT = "方向鍵左", DPRIGHT = "方向鍵右",
        A = "A", B = "B", X = "X", Y = "Y",
        LEFTSHOULDER = "左肩鍵", RIGHTSHOULDER = "右肩鍵",
        LEFTSTICK = "按下左搖桿", RIGHTSTICK = "按下右搖桿",
        BACK = "Back", START = "Start", GUIDE = "Guide",
        TRIGGERLEFT = "左扳機", TRIGGERRIGHT = "右扳機",
        CHORD = "{mod}+{button}",
    },

    MISC = {
        LOADED = "Blindfold {version} 已載入。",
        UPDATE_AVAILABLE = "Blindfold有可用更新：{current}到{latest}。",
        TUTORIAL_DONE = "教學完成。",
    },
    RARITY = { COMMON = "普通", UNCOMMON = "罕見", RARE = "稀有", LEGENDARY = "傳奇" },
    POSITION = { OF = "第{index}個，共{total}個" },

    SCREEN = {
        PLAYING      = "遊戲中",
        SHOP         = "商店",
        BLIND_SELECT = "選擇盲注",
        CASH_OUT     = "結算",
        PACK         = "擴充包",
        GAME_OVER    = "遊戲結束",
        MAIN_MENU    = "主選單",
        MENU         = "選單",
    },

    MENU = {
        DISCORD = "Discord",
        TWITTER = "Twitter",
        CONFIRM_UNLOCK = "確認全部解鎖",
        CONFIRM_ACTION = "確認{action}",
        COMPLETED      = "已完成",
    },

    CONTAINER = {
        HAND        = "手牌",
        JOKERS      = "小丑牌",
        CONSUMABLES = "消耗牌",
        VOUCHERS    = "禮券",
        PACKS       = "擴充包",
        DECK        = "牌組",
        PLAYED      = "已打出",
        SHOP        = "商店",
        SHOP_GOODS  = "禮券與擴充包",
        PACK        = "擴充包",
    },

    PACK = {
        CHOOSE    = "從{count}張中選擇{choices}張",
        CANT_SKIP = "無法跳過",
    },

    CARD = {
        PLAYING    = "{suit}{rank}",
        DEBUFFED   = "被削弱",
        FACE_DOWN  = "背面朝上",
        TELL_SMALL    = "小尺寸卡牌",
        TELL_SQUARE   = "正方形卡牌",
        TELL_HALF     = "半高卡牌",
        TELL_SHORT    = "矮卡牌",
        TELL_RED_BACK = "紅色牌背",
        SELL       = "售價{amount}$",
        CANT_SELL  = "無法賣出",
        PINNED     = "已釘選",
        NEW        = "新",
        FORCED     = "強制選取",
        WIN_STICKER = "{stake}貼紙",
        SELECTED   = "已選取",
        DESELECTED = "已取消選取",
        TIP        = "{name}，{desc}",
        RANDOM_MULT = "+{min}至+{max}{mult}，隨機",
        SEL_POS    = "選擇{index}",
    },
    EDITION = {
        foil = "閃箔", holographic = "雷射",
        polychrome = "多彩", negative = "負片",
    },
    SEAL = { GOLD = "金封蠟章", RED = "紅封蠟章", BLUE = "藍封蠟章", PURPLE = "紫封蠟章" },

    INPUT = {
        NAV_UP = "向上導覽", NAV_DOWN = "向下導覽",
        NAV_LEFT = "向左導覽", NAV_RIGHT = "向右導覽",
        ROW_START = "列首", ROW_END = "列尾",
        SELECT = "選取／啟用", GRAB = "拿起／放下",
        BACK = "返回／取消選取", PAUSE = "暫停",
        PLAY_HAND = "出牌", DISCARD = "棄牌",
        SELL = "賣出", USE = "使用",
        TAB_LEFT = "上一個分頁", TAB_RIGHT = "下一個分頁",
        VIEW_DECK = "檢視牌組",
        RUN_INFO = "遊戲資訊", DEBUG_DUMP = "偵錯：輸出焦點",
        BUFFER_NEXT_ITEM = "緩衝區：下一項", BUFFER_PREV_ITEM = "緩衝區：上一項",
        BUFFER_NEXT = "緩衝區：下一個緩衝區", BUFFER_PREV = "緩衝區：上一個緩衝區",
        INFO_HANDS = "朗讀：剩餘出牌次數", INFO_DISCARDS = "朗讀：剩餘棄牌次數",
        INFO_SCORE = "朗讀：分數與目標", INFO_JOKERS = "朗讀：小丑牌欄位",
        INFO_MONEY = "朗讀：資金",
    },

    BUFFER = {
        EVENTS = "事件",
        GAME = "遊戲",
        CARD = "卡牌",
        JOKER = "小丑牌",
        CONSUMABLE = "消耗牌",
        CASHOUT = "結算",
        UI = "介面",
        NONE = "沒有緩衝區",
        EMPTY = "{buffer}緩衝區為空",
        CURRENT = "{buffer}，{item}",
    },
    GAME = {
        HANDS    = "剩餘出牌次數{count}",
        DISCARDS = "剩餘棄牌次數{count}",
        MONEY    = "{amount}$",
        SCORE    = "{score}，目標{req}",
        BLIND    = "盲注，{name}",
        ANTE     = "底注，第{ante}關，共8關",
        ROUND    = "回合，{round}",
        JOKERS   = "小丑牌{count}張，共{slots}欄",
        NOT_NOW  = "目前無法使用",
    },

    STATS = {
        USES = "使用{count}次",
    },

    DECK_VIEW = {
        NAME_DESC = "{name}：{desc}",
        TALLY     = "{label}，{count}",
        TALLY_MOD = "{label}，基礎{base}，實際{effective}",
        DRAWN     = "已抽出",
        FLIPPED   = "{count}張背面朝上抽出",
    },

    BLIND = {
        REQUIREMENT = "至少得到{amount}分",
        REWARD      = "獎勵{dollars}$",
        SKIP        = "跳過",
        NOT_CURRENT = "不是目前的盲注",
        REROLL_USED = "本底注已重擲過",
    },

    PLAY = {
        PLAY_HAND   = "出牌",
        DISCARD     = "棄牌",
        SORT_RANK   = "依點數排序",
        SORT_SUIT   = "依花色排序",
        SORTED_RANK = "已依點數排序",
        SORTED_SUIT = "已依花色排序",
        NO_CARDS    = "沒有選取卡牌",
        NO_DISCARDS = "沒有剩餘棄牌次數",
        CANT_SELECT = "無法選取",
        PICKED_UP   = "已拿起，{name}",
        PICKUP_CANCELLED = "已取消",
        SELECTION_CLEARED = "已取消選擇",
        TUT_BLOCKED = "請按照教學指示繼續",
        MOVED       = "已移動",
        PINNED_CANT_MOVE = "已釘選，無法移動",
        PLACE_LEFT    = "放到{name}左邊",
        PLACE_BETWEEN = "放到{left}和{right}之間",
        PLACE_RIGHT   = "放到{name}右邊",
        CANT_MOVE_HERE = "無法放到這裡",
        USED        = "已使用",
        CANT_USE    = "現在無法使用",
        NEEDS_TARGETS = "需要先選取手牌",
        SOLD        = "已賣出",
        CANT_SELL   = "無法賣出",
    },

    ROUND = {
        HAND_PLAYED = "已出牌，剩餘{count}次",
        DISCARDED   = "已棄牌，剩餘{count}次",
        HOOK_DISCARD   = "The Hook棄掉了{cards}",
        JOKER_DEBUFFED = "{name}被削弱",
        OX    = "資金歸零",
        TOOTH = "失去{amount}$",
    },

    SHOP = {
        COST = "{cost}$",
        FREE = "免費",
        SELL = "售價{cost}$",
        REROLL = "重擲，{cost}$",
        CANT_AFFORD = "資金不足",
        NO_ROOM     = "沒有空位",
        BOUGHT      = "已購買",
        BOUGHT_USED = "已購買並使用",
        REDEEMED    = "已兌換",
        EMPTY       = "空",
    },

    CASHOUT = {
        LABEL         = "結算",
        TOTAL         = "{dollars}$",
        ROW           = "{label}，{dollars}$",
        BLIND_ROW     = "盲注獎勵，{dollars}$",
        SAVED         = "被Mr. Bones救了一命",
        HANDS_ROW     = "剩餘出牌次數，{count}，{dollars}$",
        DISCARDS_ROW  = "剩餘棄牌次數，{count}，{dollars}$",
        INTEREST_ROW  = "利息，{dollars}$，每5$獲得{rate}，上限{max}",
        JOKER         = "小丑牌",
        TAG           = "標籤",
    },

    RUNINFO = {
        COL_LEVEL  = "等級",
        COL_CHIPS  = "籌碼",
        COL_MULT   = "倍率",
        COL_PLAYED = "打出次數",
        COL_REQS   = "要求",
    },

    EVENTS = {
        DESTROYED = "{name}被摧毀",
        ADDED     = "{name}已添加",
        HANDS     = "出牌次數{amt}",
        DISCARDS  = "棄牌次數{amt}",
        ANTE      = "底注{amt}",
        ROUND     = "回合{amt}",
    },

    SCORING = {
        HAND    = "{name}，{chips}籌碼，{mult}倍率",
        HAND_LEVEL = "{name}升到{level}級，{chips}籌碼，{mult}倍率",
        HAND_LEVEL_DOWN = "{name}降到{level}級，{chips}籌碼，{mult}倍率",
        CHIPS   = "{amt}籌碼",
        MULT    = "{amt}倍率",
        XMULT   = "乘{amt}倍率",
        ABBR_CHIPS = "籌",
        ABBR_MULT  = "倍率",
        JOKER_POS = "位置{n}的小丑牌",
        JOKER_POS_LIST = "觸發的小丑牌位置：{list}",
        DOLLARS = "{amt}$",
        DEBUFF  = "{source}被削弱",
        SOURCE  = "{source}，{effect}",
        TOTAL   = "{chips}籌碼乘{mult}倍率等於{score}",
        SCORE   = "{score}",
    },

    SET = {
        SCORING_ENABLED = "朗讀計分",
        HAND_PREVIEW    = "選牌時朗讀牌型",
        SCORING_DETAIL  = "計分詳細程度",
        DETAIL_FULL     = "完整",
        DETAIL_JOKERS   = "僅小丑牌",
        DETAIL_SUMMARY  = "摘要",
        ROUND_ACTIONS   = "朗讀出牌與棄牌",
        KEYBINDS        = "按鍵設定",
        ANNOUNCEMENTS   = "朗讀設定",
        TUTORIAL        = "遊玩教學",
        UNAVAILABLE     = "Blindfold設定無法使用",
        PRESS_KEY       = "請按下要指派給{action}的按鍵或手把按鈕",
        BOUND           = "{action}已綁定到{key}",
        CANCELLED       = "已取消重新綁定",
        CONFLICT        = "{key}已綁定到{action}，已取消重新綁定",
        CLICK_ORDER     = "按選擇順序計分卡牌",
        CURSOR_FOLLOW   = "遊戲游標跟隨導航",
        ANN_TYPE        = "朗讀類型",
        ANN_SUBTYPE     = "朗讀稀有度",
        ANN_SELECTED    = "朗讀選取狀態",
        ANN_DESCRIPTION = "朗讀描述",
        ANN_TOOLTIP     = "朗讀提示",
        ANN_EXTRAS      = "朗讀選項資訊",
        ANN_POSITION    = "朗讀位置",
        ANN_CONTAINER   = "朗讀區域",
        ANN_SCREEN      = "朗讀畫面切換",
        ANN_KEYWORDS    = "朗讀關鍵詞說明",
        EV_TAGS         = "播報標籤效果",
        EV_CARDS        = "播報創建和摧毀的卡牌",
        EV_RESOURCES    = "播報資源變化",
        DISCORD         = "造訪Discord",
        PATREON         = "在Patreon上支持我們",
        OPENING_DISCORD = "正在瀏覽器中開啟Discord。",
        OPENING_PATREON = "正在瀏覽器中開啟Patreon。",
        VIEW_DOCS       = "檢視文件",
        VIEW_CHANGES    = "檢視更新內容",
        OPENING_DOCS    = "正在開啟文件。",
        OPENING_CHANGES = "正在開啟更新內容。",
        SPEECH_BACKEND  = "語音後端",
        BACKEND_AUTO    = "自動（最佳可用）",
        SCORING         = "計分",
        FMT_CHIPS_GAIN  = "獲得籌碼播報",
        FMT_CHIPS_LOSS  = "失去籌碼播報",
        FMT_MULT_GAIN   = "加倍率播報",
        FMT_MULT_LOSS   = "減倍率播報",
        FMT_XMULT       = "乘倍率播報",
    },
}
